### ISSUE TITLE
Error message from Fabric re: wrong version of architectury?

### ISSUE THREAD

**Issue by cwb3** [Lemonszz/Biome-Makeover#101]
I'm downloading this mod for the first time, and when I try to load I'm getting the following error message: 
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Architectury' (architectury) 1.31.60 with version 4.0.30 or later.
Unmet dependency listing:
	 - Mod 'Biome Makeover' (biomemakeover) 1.18.2-1.4.18 requires version 4.0.30 or later of mod 'Architectury' (architectury), but only the wrong version is present: 1.31.60!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

I tried using a few different older versions of Archnitectury without success. Any ideas? 

Thanks

**Comment by Lemonszz** [comment]
You're using the 1.16.5 version of architectry with the 1.18.2 Biome Makeover.

https://www.curseforge.com/minecraft/mc-mods/architectury-fabric/files/3758441 is the version of architectury you want
