### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by Stevefan1769** [Lemonszz/Biome-Makeover#103]
---- Minecraft Crash Report ----
// My bad.

Time: 4/23/22 8:07 PM
Description: Initializing game

java.lang.IllegalStateException: No renderer registered for biomemakeover:mushroom_trader
	at net.minecraft.class_898.<init>(class_898.java:204)
	at net.minecraft.class_310.<init>(class_310.java:527)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_898.<init>(class_898.java:204)
	at net.minecraft.class_310.<init>(class_310.java:527)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2571338136 bytes (2452 MB) / 5268045824 bytes (5024 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader)
	Fabric Mods: 
		appleskin: AppleSkin 2.4.0+mc1.16.5
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bedspreads: Bedspreads 1.3.1-1.16.4
		betterbeds: Better Beds 1.1.0
		betterbiomeblend: Better Biome Blend 1.16.4-1.2.9-fabric
		bettercaves: YUNG's Better Caves 1.16.5-1.2
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.2
		bettersodiumvideosettingsbutton: Better Sodium Video Settings Button 1.0.3.1
		betterstrongholds: YUNG's Better Strongholds 1.16.5-1.1.1
		biomemakeover: Biome Makeover 1.16.5-1.3.8
		caelus: Caelus API 0.0.12-1.16.4
		cardinal-components-base: Cardinal Components API (base) 2.8.2
		cardinal-components-entity: Cardinal Components API (entities) 2.8.2
		cinderscapes: Cinderscapes 1.4.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.14.54
		colytra: Colytra 1.3.0-1.16.4
		com_electronwill_night-config_core: core 3.6.0
		com_electronwill_night-config_toml: toml 3.6.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		comforts: Comforts 0.0.5-1.16.5
		crawl: Crawl 0.8.4
		direbats: Direbats 1.1.1+1.16.5-fabric
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.4
		dualwielding: Dual Wielding 1.0.2
		dynamicfps: Dynamic FPS 2.0.2
		dynmus: Dynamic Music 1.2.0
		endreborn: End: Rebellion 1.7.1
		enhancedcelestials: Enhanced Celestials 1.0.2
		entityculling: EntityCulling-Fabric 1.5.2
		expandedstorage: Expanded Storage 7.0.0
		fabric: Fabric API 0.42.0+1.16
		fabric-api-base: Fabric API Base 0.4.0+3cc0f0907d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+3cc0f0907d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.13+3cc0f0907d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+3cc0f0907d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+3cc0f0907d
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+3cc0f0907d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+3cc0f0907d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.5+3cc0f0907d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+3cc0f0907d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.8+3cc0f0907d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.4+3cc0f0907d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.5+3cc0f0907d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+3cc0f0907d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+3cc0f0907d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.2+3cc0f0907d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+3cc0f0907d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+3cc0f0907d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+3cc0f0907d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.1+kotlin.1.5.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.2+3cc0f0907d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+3cc0f0907d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+3cc0f0907d
		fabric-models-v0: Fabric Models (v0) 0.3.1+3cc0f0907d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+3cc0f0907d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+3cc0f0907d
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+3cc0f0907d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.6+3cc0f0907d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+3cc0f0907d
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+3cc0f0907d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.6+3cc0f0907d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+3cc0f0907d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.5+3cc0f0907d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.1+3cc0f0907d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+3cc0f0907d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.15+3cc0f0907d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.3+3cc0f0907d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.1+3cc0f0907d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+3cc0f0907d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+3cc0f0907d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+3cc0f0907d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+3cc0f0907d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+3cc0f0907d
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+3cc0f0907d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.8+3cc0f0907d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+3cc0f0907d
		fabric-tree-chopper: Fabric Tree Chopper 0.6.1
		fabricloader: Fabric Loader 0.13.3
		fallingleaves: Falling Leaves 1.6.0+1.16.5
		fastfurnace: FastFurnace 2.4
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.0
		gildedarmor: Gilded Armor 1.2.2+fabric-1.16.5
		goblintraders: Goblin Traders 1.4.1
		grass_pass: Grass Bypass 1.0.0
		harvest: Harvest 1.2.12
		illuminations: Illuminations 1.5.1
		inventoryhotswap: Inventory Hotswap 1.0
		invtrashslot: InvTrashSlot 1.0.2
		iris: Iris 1.2.2-build.30
		ironfurnaces: Iron Furnaces 2.4.1
		java: Java HotSpot(TM) 64-Bit Server VM 8
		lambdynlights: LambDynamicLights 1.3.4+1.16
		libstructure: Libstructure 1.3
		lithium: Lithium 0.6.6
		maybe-data: Maybe data 1.0.0-1.16.2
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.2
		modmenu: Mod Menu 1.16.12
		netheritehorsearmor: Netherite Horse Armor 0.4.3-1.16.3
		notenoughanimations: NotEnoughAnimations 1.2.4
		notenoughcrashes: Not Enough Crashes 4.1.4+1.16.5
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		phosphor: Phosphor 0.7.2+build.12
		ring_of_attraction: Ring Of Attraction 1.0.29
		ring_of_enderchest: Ring of Enderchest 1.0.27
		ring_of_growth: Ring Of Growth 1.0.26
		roughlyenoughitems: Roughly Enough Items 5.12.248
		roughlyenoughitems-api: REI (API) 5.12.248
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.248
		roughlyenoughitems-runtime: REI (Runtime) 5.12.248
		savemystronghold: Save My Stronghold! 1.16.4-1.0
		simplyplatinum: Simply Platinum 2.2
		skinlayers: 3d Skin Layers 1.1.0
		snowundertrees: Snow Under Trees 1.0.0
		sodium: Sodium 0.2.0+build.4
		somnus: Somnus API 0.0.12-1.16.5
		spruceui: SpruceUI 2.0.4+1.16
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		stitchedsnow: Stiched Snow 1.0.1
		team_reborn_energy: Energy 0.1.1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.2
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.2
		thonkutil: ThonkUtil 1.3
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		transliterationlib: TRansliterationLib 1.0.4
		vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
		waystones: Waystones 2.0.1
		william-wythers-overhauled-overworld: William Wythers Overhauled Overworld 1.0
		wolveswitharmor: Wolves With Armor 1.5.4-1.16.5
		yungsapi: YUNG's API 1.16.5-Fabric-8
	Launched Version: fabric-loader-0.13.3-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 580 Series GL version 4.6.14761 Compatibility Profile Context 21.30.23.04 30.0.13023.4001, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 12x AMD Ryzen 5 2600X Six-Core Processor

**Comment by Lemonszz** [comment]
Sorry, we're not supporting 1.16 anymore.

This is likely some mod incompatibility issue.
