### ISSUE TITLE
Crash upon launching game with newest Fabric API (Fabric API 0.51.1+1.18.2)

### ISSUE THREAD

**Issue by jacobmoerch** [Lemonszz/Biome-Makeover#105]
The issue can be reproduced by downloading the newest FABRIC API version.

Crash log:
[crash-2022-04-27_19.38.42-client.txt](https://github.com/Lemonszz/Biome-Makeover/files/8575174/crash-2022-04-27_19.38.42-client.txt)

**Comment by Lemonszz** [comment]
update architectury
