### ISSUE TITLE
Biome Makeover and Terrestria both introduce Saguaro Cacti

### ISSUE THREAD

**Issue by FewerFlaws** [Lemonszz/Biome-Makeover#11]
This is just a minor conflict, but both of these mods are very high quality and this is the only way in which they clash.

**Preferred resolution**
  * Terrestria uses Biome Makeover's Saguaro texture, model, and icon.  The needles stick off of the body a little, matching vanilla cacti.  And the model never creates loops when you place several blocks together.
  * Terrestria adds a composting recipe for the Saguaro to match vanilla cacti.
  * Biome Makeover uses the Terrestria Saguaro sapling so that their cactus can be grown.
  * Biome Makeover's cactus uses the terrestria texture to show that the cactus has been damaged.
  * Users may choose to hide one or the other in REI to avoid duplicates showing even though both are identical.

![2021-01-02_17 37 47](https://user-images.githubusercontent.com/75643699/103470109-a35dea80-4d22-11eb-9b16-34413ba790ab.png)

![2021-01-02_17 57 51](https://user-images.githubusercontent.com/75643699/103470199-321f3700-4d24-11eb-95ba-2af4fb28a34b.png)

**Comment by FewerFlaws** [comment]
The same issue: https://github.com/TerraformersMC/Terrestria/issues/229

**Comment by FewerFlaws** [comment]
Obiously renaming one or the other is another easy solution =]

**Comment by FewerFlaws** [comment]
Oh, the Biome Makeover saguaro actually grows from individually placed cactus blocks rather than from a sapling. That might be a better behaviour for matching vanilla.

**Comment by Lemonszz** [comment]
We're probably not going to do anything about this. 
They don't conflict in any game breaking way that warrants any action on our end imo.

**Comment by FewerFlaws** [comment]
Fair enough.  It's easy enough for me to fix it myself.  Keep up the good work.  This mod is great =D
