### ISSUE TITLE
Structures are generated floating in the air.

### ISSUE THREAD

**Issue by wasdspace** [Lemonszz/Biome-Makeover#110]
Forge: 1.18.2-40.1.19
Biome Makeover: 1.18.2-1.4.19
Architectury API: v4.4.59

See the screenshot:
![2022-05-09_13 04 19](https://user-images.githubusercontent.com/85009668/167345340-8ba7995c-d1c2-4d40-b6a6-902d1a2a17f1.png)
In the Dark Forest

**Comment by Lemonszz** [comment]
This is essentially a vanilla issue, you see the same things with modern MC structure. It's just more noticeable since the mansion is so large.

I think it looks kinda cool anyway.
