### ISSUE TITLE
[Compatibility] GhostEntity causes crash when ledger is installed

### ISSUE THREAD

**Issue by AverageTurtle** [Lemonszz/Biome-Makeover#112]
Okay so I am not sure if this is the right place to report this because idk if it is something ledger or you need to fix.

But basically what happened was flying in a badlands on my test environment for a server I am working on and the server suddenly crashed. And now the world crashes on boot.
The test env does have other mods so there is a chance it isn't a Biome Makeover or Ledger issue but that is what the crash report suggest:
[crash-2022-05-16_06.48.10-server.txt](https://github.com/Lemonszz/Biome-Makeover/files/8699419/crash-2022-05-16_06.48.10-server.txt)
[2022-05-16-7.log](https://github.com/Lemonszz/Biome-Makeover/files/8699421/2022-05-16-7.log)

Edit: Forgot to say the server is running on fabric

**Comment by Lemonszz** [comment]
Same issue as this https://github.com/Lemonszz/Biome-Makeover/issues/86

This is a ledger issue.
