### ISSUE TITLE
Performance issues on Fabric 1.18.2

### ISSUE THREAD

**Issue by itsdinkd** [Lemonszz/Biome-Makeover#113]
Looks like Tumbleweed spawner is causing high MSPT, out of 1440ms, it took 876ms (62%)

https://spark.lucko.me/aKp7rdudjB?hl=34

**Comment by Lemonszz** [comment]
This isn't directly caused by BM, it's a mod interaction with earthworks and probably something else. 
I've done what I can from my end to defend against this.
