### ISSUE TITLE
Biome Makeover causing crashes after update

### ISSUE THREAD

**Issue by Zunwolf1896** [Lemonszz/Biome-Makeover#118]
Player of mine goes online, wanders around and crashes the server, I get the following Error logs in the console, he joins three times, and each time his joining causes a crash. 

Using Fabric for 1.18.2 (0.13.3)
Biome Makeover V - 1.4.24

And the following Modpack (in case it is an incompatability) - 
https://www.curseforge.com/minecraft/modpacks/wolfqueens-origins/files/all (V7)

[crash-2022-06-03_16.04.41-server.txt](https://github.com/Lemonszz/Biome-Makeover/files/8834151/crash-2022-06-03_16.04.41-server.txt)
[crash-2022-06-03_16.10.50-server.txt](https://github.com/Lemonszz/Biome-Makeover/files/8834152/crash-2022-06-03_16.10.50-server.txt)
[crash-2022-06-03_16.15.23-server.txt](https://github.com/Lemonszz/Biome-Makeover/files/8834153/crash-2022-06-03_16.15.23-server.txt)

**Comment by Lemonszz** [comment]
Same issue as this https://github.com/Lemonszz/Biome-Makeover/issues/86

This is a ledger issue.
