### ISSUE TITLE
Minecraft 1.19 unable to load when using Biome Makeover + Oh The Biomes You'll Go Refabricated

### ISSUE THREAD

**Issue by nickademas** [Lemonszz/Biome-Makeover#123]

**Comment by greensad** [comment]
Seconded the inability to load occurs with the minimum following mods installed 
![image](https://user-images.githubusercontent.com/10079877/174359027-81c43717-6e6e-4fd3-ad32-d5004fd31017.png)

**Comment by Lemonszz** [comment]
Should be fixed for the next version!
