### ISSUE TITLE
Bugs when interacting with witch 1.19

### ISSUE THREAD

**Issue by Eatham532** [Lemonszz/Biome-Makeover#124]
![image_2022-06-13_121637292](https://user-images.githubusercontent.com/78714349/173267676-058d947a-fc99-4604-850b-ccf7e6e18f21.png)

1. While interacting with a witch with food in your hand you will eat the food.

2. As shown in the image above. The numbers overlap with the item info (Fogot what they were called)

**Comment by Lemonszz** [comment]
I can't recreate the food issue, you shouldn't be able to interact with the witch while using an item. Let me know if you have more info.

Fixed the tooltip though, should be in the next release.
