### ISSUE TITLE
Ticking Entity - Ravager

### ISSUE THREAD

**Issue by AetheriMC** [Lemonszz/Biome-Makeover#125]
_Minecraft Forge v1.18.2-40.1.0
Biome-Makeover v1.4.18_ 

**Issue**

The server seems to be crashing as a result of a ticking Ravager entity, specifically the one summoned by the Adjudicator.

[crash-2022-06-16_23.45.57-server.txt](https://github.com/Lemonszz/Biome-Makeover/files/8924624/crash-2022-06-16_23.45.57-server.txt)

**Comment by Lemonszz** [comment]
Looks like this is to do with the Crossbowverhaul mod, I'd report it to them.

**Comment by Lemonszz** [comment]
Also I'd suggest updating your BM, there's a good few bug fixes since your version.

**Comment by AetheriMC** [comment]
I'll send the crash their way and will do. Thank you!
