### ISSUE TITLE
Ticking entity again 

### ISSUE THREAD

**Issue by cfnnit** [Lemonszz/Biome-Makeover#127]
This time i shot arrow to a monster with a shield
It seems to happen when projectile hit a monster using a shield.

[crash-2022-06-18_17.37.12-server.txt](https://github.com/Lemonszz/Biome-Makeover/files/8933243/crash-2022-06-18_17.37.12-server.txt)

**Comment by Lemonszz** [comment]
This is on Terramine, specifically this code https://github.com/jakeb072001/TerraMine/blob/1.18.2/src/main/java/terramine/mixin/item/blackbelt/LivingEntityMixin.java
