### ISSUE TITLE
Game Crashes With OBYG Signs

### ISSUE THREAD

**Issue by fufihiuse** [Lemonszz/Biome-Makeover#130]
When Oh The Biomes You'll Go and Biome Makeover are enabled, placing any OBYG sign causes the game to instantly crash for anyone in the area. Players are unable to load back in, as the sign crashes before it can render.

**Comment by Lemonszz** [comment]
Is this still happening on the latest version? It should have been fixed a couple of versions ago.
If you are on the latest version, a crash report would be helpful. Thanks.

**Comment by fufihiuse** [comment]
Yep, just tested with 1.5.6

Here's the crash report!
[crash-2022-06-23_02.44.08-client.txt](https://github.com/Lemonszz/Biome-Makeover/files/8964718/crash-2022-06-23_02.44.08-client.txt)

**Comment by Lemonszz** [comment]
Fixed for 1.5.7. 

Worlds that were crashing should work fine now. Let me know if there's any more issues. Thanks for the report.

**Comment by notmaroun** [comment]
Hello, is it possible to backport this fix to 1.18.2? I'm getting sign crashes on there and I really like both your mod and BYG.

**Comment by Lemonszz** [comment]
@notmaroun, Just uploaded a backported fix.
