### ISSUE TITLE
[1.18.2] Incompatibility with Requiem mixins

### ISSUE THREAD

**Issue by Sunconure11** [Lemonszz/Biome-Makeover#134]
https://pastebin.com/GCFsx9Ar

https://pastebin.com/vc31kmSM

**Comment by Lemonszz** [comment]
I'm not entirely sure what's going on here. I'm able to load Requiem and BM with no issues.

Give it a go with the new version I just updated to CF.

**Comment by Sunconure11** [comment]
https://pastebin.com/NAfyjtth

https://pastebin.com/nwDcS5F2

**Comment by Sunconure11** [comment]
Overweight Farming and Immersive Weathering now...
