### ISSUE TITLE
Missing Sign Textures

### ISSUE THREAD

**Issue by xAlicatt** [Lemonszz/Biome-Makeover#135]
Still in the process of testing, but seemingly only getting this crash when placing (and thereby rendering) BM signs. Will update if I get any further info.

Crash Log: https://crashy.net/trZjPAZsJmsPMYXbTRl9

**Comment by Lemonszz** [comment]
Try the latest version I just uploaded.

https://www.curseforge.com/minecraft/mc-mods/biome-makeover-forge/files/3863108

**Comment by xAlicatt** [comment]
Yes, but also no. So it's not crashing anymore, but the textures are missing now. :D 
![image](https://user-images.githubusercontent.com/24724298/177865142-965f8917-7edf-4a8d-87a8-b472e5c11e19.png)

**Comment by xAlicatt** [comment]
That may be related to Sign Tools though? Testing without it... Willupdate

**Comment by Lemonszz** [comment]
Ah yeah, that makes sense. 

Not crashing is pretty good though, at least it's not going to lock anyone out of their worlds.

I'll get a proper fix out this weekend.

**Comment by Lemonszz** [comment]
I **believe** this should be fixed in the latest version.

Yell at me if it's not.
https://www.curseforge.com/minecraft/mc-mods/biome-makeover-forge/files/3864585
