### ISSUE TITLE
Crash when creating new world 1.19

### ISSUE THREAD

**Issue by soapstones** [Lemonszz/Biome-Makeover#137]
https://pastebin.com/VWy3ByxA

I get this crash when I try to create a new world.

**Comment by Lemonszz** [comment]
Interesting, this is a similar crash to #136. 

Not sure what is causing this (perhaps some common mod that's in both your pack and the other pack.

**Comment by MScott7** [comment]
Hi, I'm having a similar crash on 1.18.2. It only started happening today, after I updated Biome Makeover to 1.4.28 and Overweight Farming to 1.5. Removing Overweight Farming seems to work for me, and it's also a common mod for both of the above crash logs (both are even version 1.5). 

Here's my crash report for reference, in case it helps at all: https://pastebin.com/5Zvkp9LB

I'll try downgrading Overweight Farming versions to see if that helps, I'll edit this with my results.
Edit: surprisingly, downgrading to the next most recent version (Overweight Farming 1.4.3) doesn't reproduce my crash!

**Comment by Lemonszz** [comment]
Thanks, that helps a lot. I'll look into it.

**Comment by soapstones** [comment]
Downgrading overweight farming to the previous version seems to have fixed the problem for me as well. Thanks so much @MScott7

**Comment by Lemonszz** [comment]
Can confirm Overweight Crops 1.4.3 seems to work just fine. I've reached out to the devs to see if they can help.

**Comment by Lemonszz** [comment]
Apparently fixed on the Overweight Crops side.
