### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by justheretopostissue** [Lemonszz/Biome-Makeover#142]
i can run with architechtury and other mods that use it, however biome makeover crashes on launch

**Comment by Lemonszz** [comment]
Thanks for the report. I can't help without a crash report.

You can find them in the crash-reports folder in your Minecraft installation.

**Comment by justheretopostissue** [comment]
No crash reports were generated for the crash

**Comment by justheretopostissue** [comment]
> Thanks for the report. I can't help without a crash report.
> 
> You can find them in the crash-reports folder in your Minecraft installation.

so idk what to do about that

**Comment by Lemonszz** [comment]
You haven't given me any information such as BM version, Architectury version, MC Version, Fabric/Forge, why you think BM is causing the crash or anything else that could help identify the issue.

Your latest.log file might hold some answers.

**Comment by justheretopostissue** [comment]
BM 1.5.9, Architectury v5.10.33, mc 1.19, fabric, I am using terralith however it crashes on launch with or without it. AAH thanks for mentioning the latest.log thing, I found the issue. Dual Riders and Biome Makeover are NOT compatible for me for whatever reason

**Comment by Lemonszz** [comment]
No logs provided. can't fix.
