### ISSUE TITLE
Crash when trying to spawn witches with industrial foregoing mob duplicator

### ISSUE THREAD

**Issue by unikmhz** [Lemonszz/Biome-Makeover#145]
MC 1.18.2, Forge 40.1.68, Biome Makeover 1.4.30.
Reporting here, as mob duplicator works normally otherwise (for other mob types).
Found similar problem in an existing issue #57 , but it was already closed.
Crash report is attached: [crash-2022-08-02_07.38.26-server.txt](https://github.com/Lemonszz/Biome-Makeover/files/9239347/crash-2022-08-02_07.38.26-server.txt)

**Comment by Lemonszz** [comment]
Should be fixed for next release.
