### ISSUE TITLE
Structures Cannot Shape Terrain Properly

### ISSUE THREAD

**Issue by Blunder-G** [Lemonszz/Biome-Makeover#146]
Structures generate in coastal and steep places rather than flat and inland places. This causes them to look like they are in the air and look ugly. Example ımages: (These are litteraly the first builds I found using the /locate command)

![bugy town 1](https://user-images.githubusercontent.com/56030297/183300268-7dae808c-a6c4-4833-8ee8-f0744c4d93c7.png)
![2022-08-07_18 57 51](https://user-images.githubusercontent.com/56030297/183300272-90682e87-0697-45f7-ac65-d481fc098e1d.png)
![bugy mansion 1](https://user-images.githubusercontent.com/56030297/183300250-94904227-82d1-4b1d-9956-dbd974c7f7e3.png)
![2022-08-07_18 58 16](https://user-images.githubusercontent.com/56030297/183300254-90584d13-797c-449d-b0a7-423d77b2b41b.png)
![2022-08-07_18 55 16](https://user-images.githubusercontent.com/56030297/183300259-1a34479e-2410-4404-b0c9-724b99c2a3c8.png)

**Comment by Lemonszz** [comment]
vanilla issue. not much I can do about it.
