### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by LordDecay26** [Lemonszz/Biome-Makeover#148]
`---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 8/8/22, 1:00 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'biomemakeover'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: Trying to access unbound value 'air' from registry Registry[ResourceKey[minecraft:root / minecraft:item] (Experimental)]
	at net.minecraft.class_6880$class_6883.method_40237(class_6880.java:151)
	at net.minecraft.class_6880$class_6883.method_40230(class_6880.java:196)
	at dev.architectury.extensions.injected.InjectedRegistryEntryExtension.arch$registryName(InjectedRegistryEntryExtension.java:32)
	at dev.architectury.core.item.ArchitecturySpawnEggItem.lambda$new$0(ArchitecturySpawnEggItem.java:77)
	at dev.architectury.registry.registries.Registrar.lambda$listen$0(Registrar.java:83)
	at dev.architectury.registry.registries.fabric.RegistriesImpl$RegistrarImpl.listen(RegistriesImpl.java:285)
	at dev.architectury.registry.registries.Registrar.listen(Registrar.java:83)
	at dev.architectury.registry.registries.RegistrySupplier.listen(RegistrySupplier.java:110)
	at dev.architectury.core.item.ArchitecturySpawnEggItem.<init>(ArchitecturySpawnEggItem.java:76)
	at dev.architectury.core.item.ArchitecturySpawnEggItem.<init>(ArchitecturySpawnEggItem.java:68)
	at party.lemons.biomemakeover.init.BMItems.lambda$static$37(BMItems.java:99)
	at dev.architectury.registry.registries.fabric.RegistriesImpl$RegistrarImpl.register(RegistriesImpl.java:223)
	at dev.architectury.registry.registries.DeferredRegister.register(DeferredRegister.java:76)
	at party.lemons.biomemakeover.init.BMItems.init(BMItems.java:131)
	at party.lemons.biomemakeover.BiomeMakeover.init(BiomeMakeover.java:39)
	at party.lemons.biomemakeover.fabric.BMFabric.onInitialize(BMFabric.java:59)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.19041.867 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.19041.1620 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.19041.1741 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.19041.1741 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.2205.7 (WinBuild.160101.0800):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:10.0.19041.1151 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.19041.610 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.19041.985 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.19041.964 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.19041.1081 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Wldp.dll:Windows Lockdown Policy:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.19041.1620 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:Application Compatibility Client Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		awt.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.19041.1503 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.19041.1706 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.1.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		jna15627798212801853118.dll:JNA native library:6.1.2:Java(TM) Native Access (JNA)
		jvm.dll:OpenJDK 64-Bit server VM:17.0.1.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		ntdll.dll:NT Layer DLL:10.0.19041.1741 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.19041.844 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		svml.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		win32u.dll:Win32u:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 909176136 bytes (867 MiB) / 2264924160 bytes (2160 MiB) up to 7683964928 bytes (7328 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e84
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7239
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 126783.80
	Virtual memory used (MB): 38408.63
	Swap memory total (MB): 94208.00
	Swap memory used (MB): 531.93
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7328m -Xms256m
	Fabric Mods: 
		adorn: Adorn 3.5.0+1.18.2
		advancementplaques: Advancement Plaques 1.4.5
		alloygery: Alloygery 2.0+1.18.2
		anthropophagy: Anthropophagy 1.18-5
			reach-entity-attributes: Reach Entity Attributes 2.1.1
		appleskin: AppleSkin 2.4.0+mc1.18.2
		architectury: Architectury 4.8.80
		besmirchment: Besmirchment 1.18.2-12
			playerabilitylib: Pal 1.5.0
			terraform-wood-api-v1: Terraform Wood API (v1) 3.0.0
		better_bad_omen: Better Bad Omen 1.3.0
		betterdeserttemples: YUNG's Better Desert Temples 1.18.2-Fabric-1.3
		betterdungeons: YUNG's Better Dungeons 1.18.2-Fabric-2.1.0
		bettermineshafts: YUNG's Better Mineshafts 1.18.2-Fabric-2.2
		betterstrongholds: YUNG's Better Strongholds 1.18.2-Fabric-2.1.1
		betterwitchhuts: YUNG's Better Witch Huts 1.18.2-Fabric-1.0.1
		bewitchment: Bewitchment 1.18-23
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		biomemakeover: Biome Makeover 1.18.2-1.4.29
		blast: BLAST 1.9.1
		bookshelf: Bookshelf 13.2.48
		brazier: Brazier 4.0.3
		bwplus: Bewitchment Plus 1.18.2-17
		campfirespawnandtweaks-fabric: Campfire Spawn and Tweaks (Fabric) 1.9
		cardinal-components: Cardinal Components API 4.2.0
			cardinal-components-base: Cardinal Components API (base) 4.2.0
			cardinal-components-block: Cardinal Components API (blocks) 4.2.0
			cardinal-components-chunk: Cardinal Components API (chunks) 4.2.0
			cardinal-components-entity: Cardinal Components API (entities) 4.2.0
			cardinal-components-item: Cardinal Components API (items) 4.2.0
			cardinal-components-level: Cardinal Components API (world saves) 4.2.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.2.0
			cardinal-components-world: Cardinal Components API (worlds) 4.2.0
		castleblocks: CastleBlocks 1.0.0
		cavedust: Cave Dust 1.2.0
			kirin: Kirin UI 1.10.0-beta.2
		ce: Cave Enhancements 1.1.5
		chalk: Chalk 2.0.1+1.18.2
		chat_heads: Chat Heads 0.6.0
		chimes: Chimes 1.1.1
		cloth-api: Cloth API 3.2.64
			cloth-client-events-v0: Cloth Client Events v0 3.2.64
			cloth-common-events-v1: Cloth Common Events v1 3.2.64
			cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
			cloth-scissors-api-v1: Cloth Scissors API v1 3.2.64
			cloth-utils-v1: Cloth Utils v1 3.2.64
		cloth-config: Cloth Config v6 6.2.62
			cloth-basic-math: cloth-basic-math 0.6.1
		collective-fabric: Collective (Fabric) 4.36
			fiber: fiber 0.23.0-2
		cosmetic-armor: Cosmetic Armor 1.3.1
		crawl: Crawl 0.10.6
			mm: Manningham Mills 2.3
		creativecore: CreativeCore (Fabric) 2.6.12
		creeperspores: Creeper Spores 1.8.0
		ctov: ChoiceTheorem's Overhauled Villages 2.9
		customstars: Custom Stars 1.1+1.18.2
		darkness: True Darkness 2.0.91
		darkrites: Dark Rites 1.18.2-1
		decorative_blocks: Decorative Blocks 2.1.0
		dracomelette: Dracomelette 1.18-1
		dragonloot: DragonLoot 1.1.0
		dual_riders: Dual Riders 1.1.1
		dualwielding: Dual Wielding 1.1.0
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		dustrial_decor: Dustrial Decor 0.5
		dynview: Dynamic View Mod 1.18.2-2.2
		effective: Effective 1.2.1
		elden_horses: Elden Horses 1.0.0+1.18.2
		enchantment_lore: Enchantment Lore 1.2.6-1
			crowdin-translate: CrowdinTranslate 1.4+1.18.2
		enchdesc: EnchantmentDescriptions 10.0.4
		enhancedcelestials: Enhanced Celestials 2.0.7
		enhancedvisuals: Enhanced Visuals (Fabric) 1.5.5
		equipmentcompare: Equipment Compare 1.2.12
		fabric: Fabric API 0.58.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.23+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.1+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.19+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.2+17cbbd4360
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.23+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.10+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.10+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.3+41a02c8a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.2+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.9
		farsight: Farsight Mod 1.18-1.9
		fireworkfrenzy: Firework Frenzy 1.9
		flytre_lib: FlytreLib 1.8.1
		forgeconfigapiport: Forge Config API Port 3.2.3
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		galosphere: Galosphere 1.18.2-1.1.1
		geckolib3: Geckolib 3.0.54
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		graveyard: The Graveyard 1.9
		grindstonesharpertools-fabric: Grindstone Sharper Tools (Fabric) 2.0
		guardiansgalore: GuardiansGalore 1.18.2-3.0
		guardvillagers: Guard Villagers Fabric 1.18.2-1.0.14
		haema: Haema 1.10.1+1.18.2
			satin: Satin 1.7.2
		healingcampfire-fabric: Healing Campfire (Fabric) 3.7
		highlighter: Highlighter 1.1.2
		horsestonks: Horse Stonks 1.0.1
		iceberg: Iceberg 1.0.38
		immersive_paintings: Immersive Paintings 0.1.6+1.18.2
		immersive_weathering: Immersive Weathering 2.5.6
		incendium: Incendium + Seed Fix 5.0.4
			seedfix: Seed Fix 1.0.2
		inmis: Inmis 2.6.0-1.18.2
			omega-config: OmegaConfig 1.2.3-1.18.1
		itemborders: Item Borders 1.1.5
		jamlib: JamLib 0.0.5
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 10.1.3.240
		kiwi: Kiwi Lib 6.0.2
		legendarytooltips: Legendary Tooltips 1.2.5
		magehand: Magehand 1.1.2
		mcwfences: Macaw's Fences and Walls 1.0.6
		merchantmarkers: Merchant Markers 1.2.2
		minecraft: Minecraft 1.18.2
		miskatonicmysteries: Miskatonic Mysteries 0.1.3
			bannerpp: Banner++ 2.0.6-teb.1+mc.1.18.2
			midnightlib: MidnightLib 0.4.0
			team_reborn_energy: Energy 2.2.0
		modmenu: Mod Menu 3.2.3
		myloot: myLoot 2.1.4-1.18
		nbtcrafting: NBT Crafting 2.1.4+mc1.18.2
		nohostilesaroundcampfire-fabric: No Hostiles Around Campfire (Fabric) 4.2
		nomadbooks: Nomad Books 1.0.1
		notenoughanimations: NotEnoughAnimations 1.6.0
		npcvariety: NPC Variety 2.2.1
		numismatic-overhaul: Numismatic Overhaul 0.2.2+1.18
			stacc: Stacc 1.3.0
		ostoverhaul: Ost Overhaul 0.2.6
		overweight_farming: Overweight Farming 1.18.2-1.5.3-fabric
		owo: oωo 0.7.2-no-cme+1.18
		passiveshield-fabric: Passive Shield (Fabric) 2.3
		patchouli: Patchouli 1.18.2-71.1-FABRIC
		pehkui: Pehkui 3.4.0+1.14.4-1.19.2
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		pickupnotifier: Pick Up Notifier 3.2.0
		pickyourpoison: Pick Your Poison 1.0.8
			org_json_json: json 20211205
		pigeonpost: Pigeon Post 1.0.0
		polymorph: Polymorph 0.0.21-1.18.2
		puddles: Puddles 1.2.1
		puzzleslib: Puzzles Lib 3.3.5
		pyrotastic: Pyrotastic 1.18.2+0.0.2
		rare-ice: Rare Ice 0.4.1
		realisticfirespread: Realistic Fire Spread 1.18-1
		requiem: Requiem 2.0.0-beta.9
			automatone: Automatone 0.7.0
			blabber: Blabber 0.2.0
			chime: Chime 1.2.1
			fiber2cloth: Fiber To Cloth 3.1.1
			impersonate: Impersonate 2.5.0
			locki: Locki 0.7.0
			requiem-core: Requiem-Core 2.0.0-beta.9
			requiemapi: Requiem-API 2.0.0-beta.9
		respawnablepets: Respawnable Pets 1.18-4
		rightclickharvest: Right Click Harvest 2.2.1+1.18
		rpg-hud: RPG-Hud 3.9.2
		rpgstats: RPGStats 4.3.13+1.18.2
			autoconfig1u: Auto Config v1 Updated 3.4.0
			libgui: LibGui 5.4.1+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
			server_translations_api: Server Translations API 1.4.12+1.18.2
				packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		shwfox: Shadew's Foxes 1.3+fabric
		skinlayers: 3d Skin Layers 1.4.6-mc1.18.2
		skylorlib: SkyLib 1.3.35
		snowrealmagic: Snow! Real Magic! 4.1.2
		softerhaybales-fabric: Softer Hay Bales (Fabric) 1.9
		spoornpacks: SpoornPacks 4.2.3-1.18.2
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.13.1
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.13.1
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.13.1
		starterkit-fabric: Starter Kit (Fabric) 3.5
		stylisheffects: Stylish Effects 3.1.0
		sulfurpotassiummod: Sulfur & Potassium 1.1.2
		t_and_t: Towns and Towers - Structure Add-on 1.6
		terrablender: TerraBlender 1.1.0.102
		travelerstitles: Traveler's Titles 1.18.2-Fabric-2.1.1
		tree-hollows: Tree Hollows 1.3.3
			tree-hollows-core: Core 1.3.3
		trinkets: Trinkets 3.3.1
		twigs: Twigs 1.1.3-patch2+1.18.2
		vanilla_degus: Vanilla Degus 1.3.0
		villagespawnpoint-fabric: Village Spawn Point (Fabric) 2.2
		visuality: Visuality 0.4.2
			goosik-config: goosik-config 0.2.0
			tlcosmetica: Cosmetica 0.4.0
		wandering_collector: Wandering Collector 1.1.2+mc1.18.2
			coat: Coat 1.0.0-beta.17+mc1.18.2
			tweed4_annotated: tweed4_annotated 1.3.0
			tweed4_base: tweed4_base 1.5.0+mc1.18.2
			tweed4_data: tweed4_data 1.2.1+mc1.18.2
			tweed4_data_hjson: tweed4_data_hjson 1.1.0
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.2+mc1.18.2
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc1.18.2
		wandering_trapper: Wandering Trapper 1.2.0
		waveycapes: WaveyCapes 1.2.0
		whisperwoods: Whisperwoods 1.18.2-2.1.0
		woof: Woof 1.1.2-1.18
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.7
			com_github_llamalad7_mixinextras: MixinExtras 0.0.12
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.8
		yungsbridges: YUNG's Bridges 1.18.2-Fabric-2.1.0
		yungsextras: YUNG's Extras 1.18.2-Fabric-2.1.0
	Launched Version: fabric-loader-0.14.9-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>`
	
	Game crashes on startup, not sure what's causing it, the logs dont tell me anything useful. It's definitely this mod as well, uninstalling it fixes the issue.

**Comment by Lemonszz** [comment]
Same as #147 

Looks to be an Arch issue, either upgrade your Architectury version once it's fixed or downgrade a few architectury versions.

**Comment by LordDecay26** [comment]
i've downgraded all the way to the oldest version of architectury for fabric 1.18.2, every time it's still broken.

**Comment by Lemonszz** [comment]
try the latest, they've fixed it now. post a log if it still happens
