### ISSUE TITLE
Server crashes when a ghost is ticked

### ISSUE THREAD

**Issue by DaenenTDD** [Lemonszz/Biome-Makeover#149]

**Comment by Lemonszz** [comment]
can't help without a crashlog, but my guess is that you need to update ledger.

**Comment by DaenenTDD** [comment]
Weird, I attatched the log, didnt go through or something i guess.
Can I use ledgers latest version even if its not for the version I am running? The latest version of ledger is made for 1.19, I am on 1.18.2
[crash-2022-08-11_18.49.05-server.txt](https://github.com/Lemonszz/Biome-Makeover/files/9311653/crash-2022-08-11_18.49.05-server.txt)

**Comment by Lemonszz** [comment]
If you download the "build-artifacts" .zip from here https://github.com/QuiltServerTools/Ledger/actions/runs/2443821453

It contains ledger-1.2.4.build.569.jar which is a known working version.
