### ISSUE TITLE
Crash with latest update (Fabric 1.19)

### ISSUE THREAD

**Issue by MarioAndWeegee3** [Lemonszz/Biome-Makeover#154]
Minecraft Version: 1.19.2

- Mod Version: 1.5.12
- Fabric Loader Version: 0.14.9
- Fabric API Version: 0.60.0+1.19.2
- Architectury Version: 6.2.43

Also tested with Quilt:

- Quilt Loader Version: 0.17.3
- Quilted Fabric API Version: 4.0.0-beta.9
- Quilt Standard Libraries Version: 3.0.0-beta.14

[Fabric Crash Log](https://mclo.gs/kMKNKO6)
[Quilt Crash Log](https://mclo.gs/y1iuMdp)

**Comment by Lemonszz** [comment]
Thanks for the report!

Looks like I accidentally uploaded the wrong file to Modrinth. 

Should be fixed now 👍 https://modrinth.com/mod/biome-makeover/version/fabric-1.19.2-1.5.12
