### ISSUE TITLE
Potential Incompatibility with Epic Fight mod on Forge 1.18.2

### ISSUE THREAD

**Issue by Gelox1209** [Lemonszz/Biome-Makeover#155]
I'm assuming this is caused by Epic Fight, but I'm unsure.

Halfway through the Adjudicator boss fight, the server crashed.

Here's the server log:
[biomemakeoverepicfightcrash.log](https://github.com/Lemonszz/Biome-Makeover/files/9386125/biomemakeoverepicfightcrash.log)

**Comment by Lemonszz** [comment]
Yeah this is epic fight's crash. You should report it to them. Should be a fairly easy fix on their end.
