### ISSUE TITLE
Ticking player disconnect when picking up a item affected by a biomemakeover curse 

### ISSUE THREAD

**Issue by masmasmas66** [Lemonszz/Biome-Makeover#160]
[log.txt](https://github.com/Lemonszz/Biome-Makeover/files/9538578/log.txt)
Quilt 1.19.2
Happened on multiplayer of course, didn't test in the other loaders.
The curses were granted to the items with the EnchantGiver mod if that's important.

**Comment by Lemonszz** [comment]
This is likely the result of incompatible enchantments being put on the same item, not really sure how to reproduce, but if you have more information, let me know,
