### ISSUE TITLE
Slime- / Honey Blocks in the 1.18.1-1.4.8 Version are bugged

### ISSUE THREAD

**Issue by Smuthytrinker** [Lemonszz/Biome-Makeover#161]
Hey hey,
Slime/Honey Blocks don't work correctly on the 1.18.1-1.4.8 Version of this mod.

Bug (with Biom-Makeover)
![dddddddddddddddddd](https://user-images.githubusercontent.com/62059770/189975310-742f4155-e5f7-4ca4-ba16-c392b8704635.PNG)

How it should work
![dddddddddddddddddd2](https://user-images.githubusercontent.com/62059770/189975319-311e3cdf-5073-4613-a2fe-833d34e5db93.PNG)

With this bug it's Impossible to make complex Sticky block contractions. Is there a way to fix that?

**Comment by Lemonszz** [comment]
We're no longer supporting 1.18.1.

I can't recreate this in 1.18.2 either. BM doesn't touch anything to do with honey or slime blocks, are you sure this is a BM issue and not some other mod?

**Comment by Smuthytrinker** [comment]
Yes its 100% an BM issue. Its when sticky blocks are attatch to each others + some random moveble blocks. We found some files in the 18.1 Mod code for Sticky blocks aswell as pistons. Maybe that changed something?

**Comment by Lemonszz** [comment]
Can you link me to this code?

**Comment by Smuthytrinker** [comment]
biomemakeover-FABRIC-1.18.1-1.4.8.jar\META-INF\jars\MoreTags-2.0.3.jar\net\gudenau\minecraft\moretags\mixins\stickyblocks\PistonHandlerMixin.class

**Comment by Smuthytrinker** [comment]
1. biomemakeover-FABRIC-1.18.1-1.4.8.jar\META-INF\jars\MoreTags-2.0.3.jar\net\gudenau\minecraft\moretags\mixins\stickyblocks\PistonHandlerMixin.class

2. biomemakeover-FABRIC-1.18.1-1.4.8.jar\META-INF\jars\MoreTags-2.0.3.jar\data\c\tags\blocks\sticky_blocks

**Comment by Lemonszz** [comment]
I see. Not caused by BM, but a dependency for that version. I'd report that here https://github.com/gudenau/minecraft-MoreTags

**Comment by Kierecko** [comment]
@Lemonszz wait but it's mentioned nowhere as dependency?

**Comment by Lemonszz** [comment]
It's included internally in some versions.

**Comment by Kierecko** [comment]
oh, okay, but how would we solve the issue then even if we reported it to more-tags and they changed something?

**Comment by Lemonszz** [comment]
Ideally, you'd update from 1.18.1 as we're not supporting it anymore.

If you open up the biome makeover .jar file in winrar/7zip then:
 - replace the MoreTags .jar in the META-INF/jars folder  
 - edit the bottom of the fabric.mod.json file to point to the new jar
 
 It *might* work. But like I said, 1.18.1 is out of our support range, sorry.

**Comment by Kierecko** [comment]
That's already super helpful and I hope we can make this work! Thanks for still responding so fast eventhough you don't support 1.18.1 anymore!
