### ISSUE TITLE
Numbers are rendered above item descriptions in haggling things

### ISSUE THREAD

**Issue by thelegitdolt** [Lemonszz/Biome-Makeover#164]
<img width="1512" alt="Screen Shot 2022-09-30 at 7 28 28 PM" src="https://user-images.githubusercontent.com/50085439/193379653-afa882ab-0528-448e-aa3b-1bfdd6e3745e.png">

**Comment by Lemonszz** [comment]
Thanks for the report. 
This is fixed in newer (1.19) versions. We're unlikely to backport the fix unfortunately.

**Comment by thelegitdolt** [comment]
alright! my bad
