### ISSUE TITLE
Illunite crystal does not want its assigned texture

### ISSUE THREAD

**Issue by lxly9** [Lemonszz/Biome-Makeover#167]
Im making a parity pack with the cluster model by stridey. I renamed the files, textures, etc. to illunite_cluster_day/night/unknown plus textures and mcmeta. It accepts the custom model, but does not want to use the texture. (variants display correctly, the model changes based off day/night). Folder structure is completely correct, as seen by the other models and textures from different mods.

**Comment by Lemonszz** [comment]
There's no special rendering or anything with them.

Make sure you've got the right `biomemakeover` domain in your folders & in the model files.  
If you can post a screenshot of your folder structure and your model files I can probably verify if they're correct.

**Comment by lxly9** [comment]
Yess of course!
![image](https://user-images.githubusercontent.com/102386118/194787744-40f5601e-fa70-43a0-8e93-3d2e1f4f1536.png)
![image](https://user-images.githubusercontent.com/102386118/194787763-d5ca3534-f91f-4b72-b72b-0187cebcbef2.png)
[illunite_cluster_day.txt](https://github.com/Lemonszz/Biome-Makeover/files/9742915/illunite_cluster_day.txt)

**Comment by lxly9** [comment]
oh, i noticed, the screenshot with the texture is a bit older, it was before i renamed it to _day

**Comment by Lemonszz** [comment]
Easy fix, in the models, the texture should be 

`biomemakeover:block/illunite_cluster_day`

You just have the `block/illunite_cluster_day`

**Comment by lxly9** [comment]
hmmm weird, for every other modded texture it did work, but thank you very much!!
