### ISSUE TITLE
Compat issue with Lootr?

### ISSUE THREAD

**Issue by axijiku** [Lemonszz/Biome-Makeover#168]
I've had Biome Makeover for some time now, (loving it btw) but when I went to install Lootr and its dependencies I was met with this crash:

https://mclo.gs/YLuwEpM

Not sure if this is their issue or if it's your mod that has a problem with it. Appreciate your time!

**Comment by Lemonszz** [comment]
Not sure about this one at first glance. 
Looks to be a similar issue we had with texture sheets being loaded.

You should send this report off to them in case they can fix it from their end, I don't have time to do a proper deep dive on it right now.

**Comment by axijiku** [comment]
No worries, I appreciate your help regardless.
I'll definitely check out if its an issue that they'd be able to fix.

Again thanks for your time!

**Comment by Lemonszz** [comment]
Closing this as there hasn't been any more reports - feel free to reopen if this is still an issue.
