### ISSUE TITLE
Was "helmit" intentionally misspelled? There are hermit crabs and helmet crabs.

### ISSUE THREAD

**Issue by JalapenoGremlin** [Lemonszz/Biome-Makeover#170]
Based upon the rendering and location, I think that the crabs in Biome Makeover are hermit crabs. 

Might be hard to change the identifiers in the code and maintain backwards compatibility.

**Comment by Lemonszz** [comment]
Yeah this is intended. 

It's a pun, they're hermit crabs that wear helmets.
