### ISSUE TITLE
Make Woodland Mansions more configurable via datapack

### ISSUE THREAD

**Issue by rafaelkai** [Lemonszz/Biome-Makeover#176]
I requested a datapack to make the new mansions added by repurposed structures generate in the style of Biome Makeover Mansions, but I received this response:

![Qa9tM9t](https://user-images.githubusercontent.com/72790002/200165074-a780bc0d-dd22-43ba-a16d-a3a08553a385.png)

Is there any chance you could make Mansions more configurable via datapacks? Cheers.

**Comment by Lemonszz** [comment]
It's on the list of things to do, but fairly low priority.

**Comment by Lemonszz** [comment]
This is done for the next release 👍
