### ISSUE TITLE
Helmit Crabs crash the world when wearing certain modded helmets (fabric)

### ISSUE THREAD

**Issue by BabblingFishes** [Lemonszz/Biome-Makeover#177]
Some helmets, such as the Bumblezone's Stingless Bee Helmet or Deeper and Darker's Warden Helmet, will crash the world when picked up by Helmit Crabs. The world will then crash every time it's opened.

Other helmets, such as Twilight Forest's Knightmetal Helmet, do not crash, but only turn the shell to the black/pink error texture.

This crash can be recreated using:
- Minecraft 1.19.2 (singleplayer client)
- Fabric loader version 0.14.10-1.19.2
- fabric-api-0.64.0+1.19.2
- biomemakeover-FABRIC-1.19.2-1.5.12
- architectury-6.3.49-fabric
- the_bumblezone_fabric-6.3.1+1.19.2

Logs:
[latest.log](https://github.com/Lemonszz/Biome-Makeover/files/9966703/latest.log)
[crash-2022-11-08_18.06.07-client.txt](https://github.com/Lemonszz/Biome-Makeover/files/9966705/crash-2022-11-08_18.06.07-client.txt)

**Comment by Lemonszz** [comment]
Fixed for next update
