### ISSUE TITLE
Foxglove and Black Thistle are not tagged minecraft:tall_flowers

### ISSUE THREAD

**Issue by TelepathicGrunt** [Lemonszz/Biome-Makeover#180]
Noticed this when testing All of fabric 6 modpack in 1.19.2. The other two tall flowers from Biome Makeover are tagged as tall flowers. Just something small so bees can pollinate these flowers

![image](https://user-images.githubusercontent.com/40846040/202873059-bdd1de9e-3d62-424f-a568-e6175648a0e3.png)
![image](https://user-images.githubusercontent.com/40846040/202873066-7a655e05-5286-4352-9fee-aae62d3f39a6.png)

**Comment by Lemonszz** [comment]
fixed for next release
