### ISSUE TITLE
[1.19.2] Moth pathfinding gets stuck in Bumblezone's Hanging Garden structure.

### ISSUE THREAD

**Issue by TelepathicGrunt** [Lemonszz/Biome-Makeover#181]
Bumblezone is my mod and in it, I have a Hanging Garden structure with lots of flowers and I spawn some insect mobs from other mods. One of them is Biome Makeover's Moth. However, I witness the moth will always keep trying to pathfind onto my Glistering Honey Crystal block while between the Super Candle and a Honey Crystal. I have no idea why it is getting stuck. These blocks do give off light and have different hitboxes. Even when I make the candle unlit, the moth is still stuck. I then removed the candle and the Honey Crystal so only the Glistering Honey Crystal in the floor is left and moth still pathfinds and gets stuck right on top of it spinning.

This is occurring on both Forge and Fabric 1.19.2 with latest version of both of our mods. No clue what's going on here

https://user-images.githubusercontent.com/40846040/202877781-e8e6e939-445b-49b8-b8c4-8a83c91a2133.mp4

https://user-images.githubusercontent.com/40846040/202877819-0469dbfa-1ca0-4562-93f0-dd554c929120.mp4

**Comment by Lemonszz** [comment]
I've redone moth AI for our next release. Not sure if this will still happen, it's a lot closer to Bee AI, now, so I assume it'll be better lol.
