### ISSUE TITLE
[1.18.2] Crash between Biome Makeover's Itching Ivy and Farmer's Delight Rich soil

### ISSUE THREAD

**Issue by Insane96** [Lemonszz/Biome-Makeover#182]
Crashlog: https://gist.github.com/Insane96/395489cf53a596b11e8720a020e94684

Also reported to https://github.com/vectorwing/FarmersDelight/issues/593

**Comment by Lemonszz** [comment]
This is on BM's end. I think I already fixed this for 1.19.

I'm not supporting 1.18.2 anymore, but I'll leave this issue open for others to find.

if anyone wants to backport a fix. Lemme know.
