### ISSUE TITLE
[1.19.2] Missing subtitle translation for scuttler's death 

### ISSUE THREAD

**Issue by 0rc1nus** [Lemonszz/Biome-Makeover#184]
I was doing a bit of testing in my modpack and I realized the sound of scutter's death is missing a translation.

Also another completely unrelated note, I don't know if I should create another issue or not but glowfish has 10 hearts. So I'm not entirely sure whether this is an oversight or a feature.

**Comment by Lemonszz** [comment]
Fixed both for next release
