### ISSUE TITLE
1.18.2 abandoned?

### ISSUE THREAD

**Issue by BrekiTomasson** [Lemonszz/Biome-Makeover#185]
I see no 1.18.2 release since Aug 19 this year. Is there any chance that the development progress in the 1.19 branch will ever be back-ported to 1.18? Like so many others, I'm still stuck on 1.18 in my modpack since so many mods haven't been updated yet.

**Comment by Lemonszz** [comment]
There was actually a 1.18.2 release about a month ago, it's on the 1.18 branch, not the 1.18.2 one (just just to confuse people).

Regardless, I'm not doing any 1.18.2 stuff myself, but others are welcome to backport any fixes.

**Comment by BrekiTomasson** [comment]
I'm not seeing this release on Modrinth. Did it not make it to there?
