### ISSUE TITLE
Mod Compat

### ISSUE THREAD

**Issue by PercyJames** [Lemonszz/Biome-Makeover#190]
Hello! I have a suggestion for mod compat. maybe you could add tapestries for these mods one day?

 

https://www.curseforge.com/minecraft/mc-mods/tinted

 

https://www.curseforge.com/minecraft/mc-mods/flamboyant-recrafted

 

flamboyant is probably updating to 1.19. Also some of the colors have the same names between both mods.

**Comment by Lemonszz** [comment]
Thanks for the suggestion! 
While it would be cool, we're not likely to add support ourselves, just because of the effort involved.

Someone else would be free to make an addon to do it if they want.

**Comment by PercyJames** [comment]
ok! Let's hope!
