### ISSUE TITLE
Witch Hat is rendered in a wrong/incompatible way for First-person Model.

### ISSUE THREAD

**Issue by Meow-Bots** [Lemonszz/Biome-Makeover#191]
The witch hat blocks 1/4 of the screen when I look forward.
It will block half of the screen if I look down while wearing it.
I talked to the developer of First-person Model, and they told me that its Biome Makeover render problem.
![2023-01-07_18 03 14](https://user-images.githubusercontent.com/40931331/211173778-59ba13cf-2255-4f4d-b84d-f6c6156bfd47.png)
![2023-01-07_18 03 23](https://user-images.githubusercontent.com/40931331/211173780-4f48c7c2-919c-426e-b49f-4adf7d70e797.png)
![2023-01-07_18 10 20](https://user-images.githubusercontent.com/40931331/211173782-f879abe2-4584-4dd6-84f2-2d7dfba41881.png)

**Comment by Lemonszz** [comment]
Hi, sorry for the late reply. 

There's not really much I can do about this on my end. This would be on the first person mod to cull.
