### ISSUE TITLE
Mixin injection error on biomemakeover-FABRIC-1.19.3-1.7.1 relating to "taniwha"

### ISSUE THREAD

**Issue by chexo3** [Lemonszz/Biome-Makeover#192]
I'm not sure exactly what that is, I'm guessing a library of some sort? It was referenced in the crash log and I found a jar for it inside this mod's jar. Reading the crash log, it seems to be related to a mixin injection not working. It crashes on loading.

Minecraft version 1.19.3
Java 17.0.3 from Eclipse Adoptium
Windows 10
+Many other mods (see log below)

Log file here: [[LINK]](https://gist.github.com/chexo3/711712a99f472a9720781a15c226a7de)

**Comment by Lemonszz** [comment]
Yeah - That's my library. 

Looks to be BM and another mod trying to do the same redirect in the CropBlock class.
If you happen to work out what mod that is, that would be very helpful in tracking it down, but I can look into it another time.

Thanks for the report.

**Comment by chexo3** [comment]
I removed your mod for now. I'm not sure what tools there are to figure out what other mods are redirecting in that class. I have only very basic experience with Mixins.

**Comment by Lemonszz** [comment]
This should be fixed in future versions.
