### ISSUE TITLE
1.19.3 helmit crab crashes game (party.lemons.biomemakeover.entity.HelmitCrabEntity)

### ISSUE THREAD

**Issue by VegaVoid1674** [Lemonszz/Biome-Makeover#197]
My game has crashed multiples times in the same spot of the same world, in a tropical area with water. I assume its when this helmit crab entity spawns.

[crash-2023-02-05_00.54.54-client.txt](https://github.com/Lemonszz/Biome-Makeover/files/10610322/crash-2023-02-05_00.54.54-client.txt)

**Comment by Lemonszz** [comment]
Looks like an issue with "Headed".

Not sure if it's our fault or theirs, but something is assuming our crab is a "ModelWithHead".

I don't have much time to look into it right now, but it might be worth reporting it to them.

**Comment by VegaVoid1674** [comment]
Thanks for the fast response! I will probably remove Headed from my modpack, then.
