### ISSUE TITLE
[1.19.2] Crash, probably incompatibility with effective

### ISSUE THREAD

**Issue by benio1394** [Lemonszz/Biome-Makeover#199]
https://pastebin.com/RuEJ6bxL

**Comment by Lemonszz** [comment]
Hello - Late response man here, I believe this is a Effective crash being falsely blamed on Biome Makeover for some weird reason. 

We're not supporting 1.19.2 anymore, but I'd suggest trying without Biome Makeover, if it still happens, it's not BM.
If it does still happen it likely is some compatibility issue.

If you can recreate this on 1.19.4+ please let me know.
