### ISSUE TITLE
Ghost town building interiors can be buried in stone/terracotta

### ISSUE THREAD

**Issue by saltyseadoggo** [Lemonszz/Biome-Makeover#20]
As per the title, I found a ghost town in a world generated with seed 5018746510160316681 at 20, 70, 220 in which most of the buildings have some or all of their rooms filled partially or completely with stone and terracotta from mesa formations that they were partially buried in. The ghosts are also missing; would the obstructions have stopped them from spawning?

Somehow forcing the buildings to generate air in their interiors would resolve at least the interior obstructions, surely, but I'm not sure how you might prevent them from spawning partially buried to begin with.

![2021-01-08_23 48 47](https://user-images.githubusercontent.com/69029346/104086434-f0ebc300-520c-11eb-90f7-5a00682b857d.png)
![2021-01-08_23 49 14](https://user-images.githubusercontent.com/69029346/104086435-f1845980-520c-11eb-91bf-596ae37a17a9.png)
![2021-01-08_23 54 58](https://user-images.githubusercontent.com/69029346/104086436-f21cf000-520c-11eb-9e38-3878bc32eb77.png)

**Comment by Lemonszz** [comment]
This is an unfortunate vanilla bug that I was unable to fix. It will happen on occasion with vanilla villages.
