### ISSUE TITLE
[1.18.2]  Incompatibility with Biomes You'll Go's Bayou

### ISSUE THREAD

**Issue by Reshy** [Lemonszz/Biome-Makeover#201]
Seems like there's an incompatibility with BYG that causes water silk, lilypads, and end lily (yes in the end) to sometimes spawn under the water.  Biome Makeover plants will also similarly spawn as if these plants were solid blocks.  Only seems to happen with Biome Makeover and BYG installed together.

![2023-02-14_21 58 15](https://user-images.githubusercontent.com/2096384/218945469-d5485374-61f5-48f5-aeee-56cd4ab4c7f9.png)

![2023-02-14_22 02 48](https://user-images.githubusercontent.com/2096384/218945804-7ef95da0-c206-424e-a29d-09e9c5b98366.png)

**Comment by Lemonszz** [comment]
We're not supporting 1.18.2 anymore, so this won't be of much help, but I do believe this was fixed in a later version.

If you can recreate this on 1.19.4+, please let me know!
