### ISSUE TITLE
Stone golem suffocates without oxygen on Ad Astra planets

### ISSUE THREAD

**Issue by James103** [Lemonszz/Biome-Makeover#206]
The Stone Golem entity added by this mod, `biomemakeover:stone_golem`, currently suffocates to death within 30 seconds if summoned on an Ad Astra planet.

To reproduce,
1. Create a new instance with Minecraft 1.19.2 and Fabric Loader 0.14.17.
2. Install Fabric API 0.76.0 and Biome Makeover 1.6.2.
3. Install Ad Astra 1.12.4 or later.
4. Create a new world with cheats enabled.
5. Go to the Moon: `execute in ad_astra:moon run tp @s ~ 150 ~`
6. Summon an iron golem: `summon iron_golem`
7. Summon a stone golem: `summon biomemakeover:stone_golem`
8. Watch as the stone golem suffocates to death within 30 seconds, while the iron golem does not suffocate.

To fix:
Add the entity type `biomemakeover:stone_golem` to the tag `#ad_astra:entities/lives_without_oxygen`.

**Comment by Lemonszz** [comment]
👍 I can throw that into the next update

**Comment by Lemonszz** [comment]
Thinking on this some more - I think it would be best if this was added on ad astra's end as an optional tag. It would be a pain to add compatibility to every mod that requires something like this.

Thankfully, it should be fairly easy to make your own Data Pack/use KubeJS to add this yourself.

Sorry if that's not the result you wanted!
