### ISSUE TITLE
download is rewinding

### ISSUE THREAD

**Issue by Rogenar** [Lemonszz/Biome-Makeover#207]
In Biome Makeover 1.19.3 1.7.1, the game loading is constantly rewinding.

**Comment by Beansyboy221** [comment]
I am having the same issue. When I launch the game with this version, it keeps restarting the Mojang loading screen.

**Comment by Lemonszz** [comment]
It's unlikely this issue just appeared randomly today on BM's end. It's likely some incompatibility with some other mod.

if you post your latest.log file I can probably point you in the right direction, but I'm unlikely to do any bug fix releases for 1.19.3.

**Comment by Beansyboy221** [comment]
Here is my log: I manually closed it at the end. It didn't crash.
[latest.log](https://github.com/Lemonszz/Biome-Makeover/files/11117194/latest.log)

**Comment by Beansyboy221** [comment]
I have narrowed down the incompatibility to Better Nether / Better End. Is there a known fix for this issue?

**Comment by Lemonszz** [comment]
Not sure on this one, these issues can be hard to track down and we're not supporting 1.19.3 anymore.

I'm going to close this for now. If you can recreate this on 1.19.4+, please open a new issue with as much information as possible.
