### ISSUE TITLE
Tall mushrooms can generate on large mushrooms

### ISSUE THREAD

**Issue by saltyseadoggo** [Lemonszz/Biome-Makeover#21]
As per the title, in a world generated with seed 5018746510160316681 (the same one where I discovered #20) in a Mushroom Fields biome at 44, ~, 5844, I found a handful of large mushrooms that had generated with the new tall mushrooms growing out of them. I figured that this is unintended, so here I am to report it. This can occur with brown and red tall mushrooms, and I saw them on brown and red large mushrooms and green large glowshrooms.

![2021-01-09_00 00 59](https://user-images.githubusercontent.com/69029346/104086592-31980c00-520e-11eb-87a4-37d92f2f171d.png)
![2021-01-09_00 05 12](https://user-images.githubusercontent.com/69029346/104086631-702dc680-520e-11eb-92d7-f59a263c6cc3.png)
Four instances of this can be seen in this screenshot.
![2021-01-09_00 01 57](https://user-images.githubusercontent.com/69029346/104086593-32c93900-520e-11eb-9e02-218aee30c2b5.png)

**Comment by Lemonszz** [comment]
This is intended.
