### ISSUE TITLE
Using Lighting Bottle Crashes Game On Latest Release

### ISSUE THREAD

**Issue by TNTdisaster** [Lemonszz/Biome-Makeover#211]
Ive tested this with a completely fresh install of the mod and the same always happens, rest seems to work as intended

I dont know if you need more error information as this is just what the launcher gave me: 

"The game crashed whilst ticking entity
Error: java.lang.IllegalAccessError: class party.lemons.biomemakeover.entity.LightningBottleEntity tried to access private method 'void net.minecraft.class_1538.method_34707(net.minecraft.class_1937, net.minecraft.class_2338)' (party.lemons.biomemakeover.entity.LightningBottleEntity and net.minecraft.class_1538 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @4d49af10)"

If you need a more detailed log file i can send it.

**Comment by Lemonszz** [comment]
Thanks - this should be fixed for the next release.
