### ISSUE TITLE
Game crashes when placing a signpost(1.19.4)

### ISSUE THREAD

**Issue by ChronosV9** [Lemonszz/Biome-Makeover#212]
Game crashes whenever you place a sign made from the modded woods. 

The game crashed whilst rendering block entity
Error: java.lang.NullPointerException: Cannot read field
"field_21531" because "$$9" is null

Exit code -1

**Comment by Lemonszz** [comment]
This is fixed for the next release, but I'm leaving this open so others see it.

**Comment by Lemonszz** [comment]
This is now out
