### ISSUE TITLE
Altar curse blacklist

### ISSUE THREAD

**Issue by Treeways** [Lemonszz/Biome-Makeover#215]
I would like to disable a specific curse from the Apotheosis mod from showing up in the Altar.

Apotheosis has a config for every enchantment and curse in the game, and options for setting whether curses can be enchanted or looted from chests. It would be great if Biome Makeover was able to read the Apotheosis config and decide its enchantment pool from that file!

Otherwise, it'd be beneficial to add a blacklist elsewhere without the mod installed.
Thanks!

**Comment by Lemonszz** [comment]
This is in the latest release https://biomemakeover.laserknights.com/notes/config/tags/#enchantments
