### ISSUE TITLE
[MC 1.19.4 FABRIC] game crashes when using lightning bottle

### ISSUE THREAD

**Issue by feiudfyg** [Lemonszz/Biome-Makeover#216]
[latest.log](https://github.com/Lemonszz/Biome-Makeover/files/11471350/latest.log)
[crash-2023-05-14_14.59.21-server.txt](https://github.com/Lemonszz/Biome-Makeover/files/11471351/crash-2023-05-14_14.59.21-server.txt)
Here are the logs.

Mod version: fabric 1.19.4-1.8.3
Bug recreating; Just throw a lightning bottle and wait it to land on the ground.

Hope the bug can bed fixed soon.

**Comment by Lemonszz** [comment]
Thanks for the report- this is already fixed for an upcoming release which should be out soon
