### ISSUE TITLE
interacting with witches while wearing a witch hat causes the game to crash

### ISSUE THREAD

**Issue by LordDecay26** [Lemonszz/Biome-Makeover#221]
https://pastebin.com/5DuXfznt

**Comment by Lemonszz** [comment]
Pretty sure this is cause by "Hexerei".

Feel free to report it to them, if you have any more information that makes you think this is the fault of BM feel free to comment again and I'll have another look!

**Comment by LordDecay26** [comment]
you sure it's on their end? i cant even join the world anymore without it crashing
https://pastebin.com/QP6A2B9x
regardless, last time i reported an issue to the devs of hexeri they got really belligerent with me and when i further questioned them on it they pulled the old "well it's my mod and i release it for free and i dont appreciate you being ungrateful" and i got banned from their server. they dont seem interested in fixing errors or resolving compatibility issues of any kind, which is totally their right as it is just a hobby, but i just want to be able to join my world again.

ah well, guess im deleting this mod from the list.....

**Comment by LordDecay26** [comment]
to be clear, when i said "this mod" i mean hexerei, biome makeover is far too good of a mod to give up on that easily.

**Comment by Lemonszz** [comment]
I'm not 100% it's on their end, but that's what the original log seemed to be pointing towards. The 

We're not officially supporting 1.19.2, but if you remove Hexerei and the issue persists, feel free to hop into our Discord and we can try and troubleshoot it further.

**Comment by Lemonszz** [comment]
I'd suggest making a backup before you remove it though - in case that doesn't solve the issue and you want to keep using the mod

**Comment by Lemonszz** [comment]
I just did a couple of tests to confirm my suspicions. I was able to recreate the issue.

- Hexerei + Biome Makeover = Crash
- Just Biome Makeover = All Good
- Just Hexerei = Crash

To me that confirms this is not a BM issue. Though it's possible there is some compat issue that could be ironed for out 1.20 plus, as it was two different crash reasons, but I'll cross that bridge when it comes up.

**Comment by LordDecay26** [comment]
thank you sir. yeah i removed hexeri and it fixed the issue.
