### ISSUE TITLE
Oversized Mushroom Villager hat

### ISSUE THREAD

**Issue by GitUser14975** [Lemonszz/Biome-Makeover#226]
A little bit too big I would say
![2023-07-10_11 13 38](https://github.com/Lemonszz/Biome-Makeover/assets/100159503/6166c65c-9f39-4fec-90b9-30120f9b0c03)

**Comment by Lemonszz** [comment]
that's... new

**Comment by Lemonszz** [comment]
I can't recreate this, It's likely some other mod you have causing the issue. 

If you could provide your latest.log file (found in your MC installation /logs) I could have a quick look, but I'm not hopeful for afix.

I'm going to close this for now, if you find more information or this pops up again, I'll reopen it.

Thanks for the report.
