### ISSUE TITLE
[1.20.1 Fabric] Buds have missing textures

### ISSUE THREAD

**Issue by gamerpotion** [Lemonszz/Biome-Makeover#227]
Hi, seems the buds have a missing texture issue when viewing in JEI type mods
Same thing in creative and in game

Version file - biomemakeover-FABRIC-1.20.0-1.10.1.jar

screenshots:-

<img src="https://media.discordapp.net/attachments/964187610392199209/1128072373464207440/image.png" />

<img src="https://media.discordapp.net/attachments/964187610392199209/1128072277737607168/image.png" />

<img src="https://media.discordapp.net/attachments/964187610392199209/1128072373464207440/image.png" />

**Comment by Lemonszz** [comment]
Can you send your latest.log file? Found in the logs folder of your MC installation.

**Comment by gamerpotion** [comment]
> Can you send your latest.log file? Found in the logs folder of your MC installation.

sure here it is - https://pastebin.com/DVGsYYa5

this is on my DarkRPG modpack btw - https://www.curseforge.com/minecraft/modpacks/darkrpg

**Comment by Lemonszz** [comment]
I tracked it down to only occurring when All The Trims and Biome Makeover and installed together, I've reported it to the All The Trims dev [here](https://github.com/Benjamin-Norton/AllTheTrims/issues/6).

**Comment by gamerpotion** [comment]
> I tracked it down to only occurring when All The Trims and Biome Makeover and installed together, I've reported it to the All The Trims dev [here](https://github.com/Benjamin-Norton/AllTheTrims/issues/6).

Thanks for looking into that! really appreciate it

**Comment by Bawnorton** [comment]
Fixed in AllTheTrims 3.1.0

**Comment by Lemonszz** [comment]
Thanks!
