### ISSUE TITLE
[1.20.1 Forge] cracked brick causes crash

### ISSUE THREAD

**Issue by kippyayo** [Lemonszz/Biome-Makeover#228]
whenever I've broken one of the large pots and picked up the cracked bricks, opening my inventory (or any inventory with them in it) causes the game to CTD. 
[latest.log](https://github.com/Lemonszz/Biome-Makeover/files/12009130/latest.log)

**Comment by Lemonszz** [comment]
I missed this - 

Strange. Looks like an incompatibility with supplimentaries. I'll look into it.

**Comment by Lemonszz** [comment]
I can't recreate this myself. Could you try with just Biome Makeover and Supplimentaries? 

I'm going to close this for now, if you find any more information I'll reopen it.

Thanks for the report!

**Comment by kippyayo** [comment]
huh. yeah after testing the two alone i cant recreate it either, i also tested them with fancy menu after reviewing the log because i thought it might be a weird interaction between the three? who knows. i simply wont pick up cracked bricks lmao

**Comment by Lemonszz** [comment]
It's *probably* some other mod you have, but it'll be tricky to track down unfortunately

**Comment by Lemonszz** [comment]
If you're still running into this, updating "SuperMartijn642's Core Lib" should fix the problem.
