### ISSUE TITLE
[crash] 1.20.1 - ancient oak sign crashes game

### ISSUE THREAD

**Issue by Xplodin** [Lemonszz/Biome-Makeover#229]
https://gist.github.com/Xplodin/6662773827ffe6a128e371dc7519bb38

I got one from a lootbundle and crashed as soon as I placed it, also making me crash whenever entering the same world

**Comment by Lemonszz** [comment]
Thanks for the report- 

I unfortunately can't recreate this on my end.

It's likely this is actually the fault of another mod that's incorrectly loading sign textures.
If this isn't your mod pack, I'd suggest reporting to the pack devs.

I'm going to close this issue for now, but if you have more information or can work out which mod may trigger this, feel free to comment and I'll reopen it. 

Sorry I couldn't be of more help!

**Comment by Xplodin** [comment]
Its alright I figured this might be on Oculus/rubidiums end as well. I reported it to them as well.
All I can tell is that normal signs work but I think the lootbundle from lootbundles mod I opened mightve had some nbt or something the sign / client didnt like
I personally think its a rendering issue but thats as far as I got

**Comment by Lemonszz** [comment]
Its not a rubidium/oculus issue.

It's less of a rendering issue and more of a technical issue. I can probably defend against this a bit more in BM, but it's still another mods issue.
