### ISSUE TITLE
[1.20.1] Crash with Ancient oak sign

### ISSUE THREAD

**Issue by CGMejia2001** [Lemonszz/Biome-Makeover#236]
Crashes when placed in the world possibly more haven't tested yet
Forge 47.1.3
Rubidium 0.7.1
Oculus 1.6.9
Minecraft 1.20.1
Biome Makeover 1.20.1-1.10.3
(If this helps I have Sinytra Connector installed so there's a bunch of fabric mods along with forge mods)

Crash report: https://gist.github.com/HaizUber/f33804305599fe82882f047c12d22f12

**Comment by Lemonszz** [comment]
Last time someone had this issue, it was caused by SuperMartijn642's Core Lib, updating that fixed it.

If that doesn't work, it's possible another mod has made the same mistake that they did and it'll be hard to track down.

**Comment by CGMejia2001** [comment]
Thanks for the fast reply, seems like updating to the latest version of SuperMartijn642's Core Lib and Config Lib didn't fixed the issue, it may be due to rubidium/oculus also tried disabling performance mods such as entity culling, enhanced block entities and seemed to only crash when that specific sign is placed

**Comment by Lemonszz** [comment]
Are other signs from Biome Makeover working, like the Willow or Blighted Balsa?

**Comment by Lemonszz** [comment]
There may be some extra information in your `latest.log` file as well, if you could post that I'll have a look.

**Comment by CGMejia2001** [comment]
Yes after testing the blighted balsa sign it crashed again

latest.log: https://gist.github.com/HaizUber/b74d5d6fdcb8794ded933dbd5629dda8
crash report after blighted balsa sign test: https://gist.github.com/HaizUber/8f6e66bb6e47c788d1ce026e9fcb421d

**Comment by CGMejia2001** [comment]
[latest.log](https://github.com/Lemonszz/Biome-Makeover/files/12755567/latest.log)
scratch that latest.log gist didn't seem to include all the lines, my bad!

**Comment by Lemonszz** [comment]
I had a look through and unfortunately, it doesn't tell me much except "some mod is breaking it".

There's not a lot I can do, sorry.

But if you do manage to find out which mod it is or you get more information, I'd love to know

**Comment by CGMejia2001** [comment]
sure thing! Thanks for your help!!

**Comment by CGMejia2001** [comment]
After some binary searching through 500 mods I found one of the culprit, seems to crash due to the Cinderscapes Fabric mod (https://modrinth.com/mod/cinderscapes/version/4.0.8)
This is likely due to Sinytra Connector(https://modrinth.com/mod/connector) not properly handling sign block entities to be compatible with forge and vice versa but not so sure, I shall report it to both sides so hopefully they can fix it in order to work with this mod and others!

Edit: More testing is being done 
![image](https://github.com/Lemonszz/Biome-Makeover/assets/95129068/e814e2b1-6882-4ca9-831a-9453c9216acb)

**Comment by Lemonszz** [comment]
Ah interesting.

I've successfully recreated the issue on my end (thanks for finding it). 

The Fabric version of BM doesn't crash, so it looks like you're correct in that it's some sort of connector issue.

This is an area of BM that's pretty "weak" and if something goes wrong, these crashes pop up. I've been meaning to fix it up as much as I can and reports like these do help with documenting and helping others - so thanks again. 

I'm planning 1 more patch for 1.20.1, so I'll see if I can get a fix in for this.

**Comment by CGMejia2001** [comment]
Thats great! thanks for working on this issue :))

**Comment by CGMejia2001** [comment]
Did some more testing, promenade(https://www.curseforge.com/minecraft/mc-mods/promenade) also causes the same issue

**Comment by CGMejia2001** [comment]
Apparently after I reported the issue to connector's dev they have a proposed fix for it already, https://github.com/Sinytra/Connector/commit/007fa070786d1fdbdbda542fcaa491868e926d1d 
i will update this issue if the issue still persists when the update rolls out

**Comment by CGMejia2001** [comment]
Updating to Connector-1.0.0-beta.17+1.20.1-full (https://modrinth.com/mod/connector/version/1.0.0-beta.17+1.20.1) fixed the issue
