### ISSUE TITLE
1.20.1 java.lang.IllegalArgumentException: No model for layer biomemakeover:cowboy_hat#main

### ISSUE THREAD

**Issue by Daltaxy** [Lemonszz/Biome-Makeover#238]
Hello, the game crashes and going back one version fixes the issue (biomemakeover-FORGE-1.20.1-1.10.3.jar)
crash report:
[crash-2023-10-05_22.27.30-client.txt](https://github.com/Lemonszz/Biome-Makeover/files/12823062/crash-2023-10-05_22.27.30-client.txt)
(Neo?)Forge 47.2.1
1.20.1

**Comment by Lemonszz** [comment]
Hm. I can't recreate this on my end, even in a large mod pack.

Could you post your `latest.log` file?

**Comment by Daltaxy** [comment]
sorry, only happens with the latest version of supplementaries for some reason.
[latest.log](https://github.com/Lemonszz/Biome-Makeover/files/12824814/latest.log)
with supplementaries, artifacts and architectury, there's another crash going so your mod is probably fine?

**Comment by Lemonszz** [comment]
`Missing or unsupported mandatory dependencies:
	Mod ID: 'moonlight', Requested by: 'supplementaries', Expected range: '[1.20-2.8.45,]', Actual version: '1.20-2.8.44'`
	
Looks like you just need to update moonlight

**Comment by Daltaxy** [comment]
that version of moonlight didn't exist yet at the time of the issue lol
thanks for your help, it's just weird that going back to previous versions didn't work though :(
