### ISSUE TITLE
[1.20.1 FORGE] Startup crash; Unable to create model for minecraft:horse

### ISSUE THREAD

**Issue by Zedrimar** [Lemonszz/Biome-Makeover#239]
Log says failed to create model for minecraft:horse due to some kind of model issue with the cowboy hat. Previous version of the mod loads up fine.

Log: https://pastebin.com/3strTJxt

Neoforge: 47.1.79
Biome-Makeover: 1.10.4
Architectury: 9.1.12

**Comment by Lemonszz** [comment]
Someone else had this issue and it turns out they needed to update moonlight #238 

Could you post your `latest.log` file?

**Comment by Zedrimar** [comment]
Oh, yeah you're right, my bad. I didn't see there was an update yet for moonlight lib since the upload was still going through curseforge's automatic scanner/pending system approval. I finally updated it (and biome-makeover) and it works just fine now. Thanks for letting me know! :)
