### ISSUE TITLE
Failed to Start MC Server - 

### ISSUE THREAD

**Issue by YejiYeah** [Lemonszz/Biome-Makeover#240]
Hi there!,

When I run the mod from the client side it's fine, however when I run the server It fails to start.

Mod version: 1.10.4
Modder: Fabric
MC Version: 1.20.1
Modpack: More mods are added, however it only have problems when this mod is updated it.

Describe how to replicate this problem:

1. Install the mod in a server.
2. Run the server.
3. The server is unable to start, a crash log is not being generated, only log (attached).

Highlighted Line: [23:41:22] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'biomemakeover'!

Thank you,
Regards
Sarah
[latest.log](https://github.com/Lemonszz/Biome-Makeover/files/12827530/latest.log)

**Comment by Lemonszz** [comment]
Oops, I can confirm this on my end - I'll get a fix out shortly!

Thanks for the report
