### ISSUE TITLE
Stone Golems don't spawn with a weapon and do not attack.

### ISSUE THREAD

**Issue by NanoAi** [Lemonszz/Biome-Makeover#243]
As per https://biomemakeover.laserknights.com/notes/mob/stone_golem/ stone golems are supposed to have crossbow.

https://github.com/Lemonszz/Biome-Makeover/assets/3096584/67d764fa-e297-4c2c-9f6b-39cb6250f941

The golem isn't attacking me, or enemies, spawns without a weapon and just sits there.

**Comment by NanoAi** [comment]
Turns out that you have to "give" them a crossbow, this should be reflected on the wiki.

**Comment by LaserDaddy** [comment]
This is intended behavior and is reflected on the wiki.

**Comment by Lemonszz** [comment]
Yeah, it does already say this on the Wiki, though is probably easy to miss under the image. 

Thanks for the report anyway!
