### ISSUE TITLE
Lilypads from Chipped use a grayscale lilypad texture when placed on water

### ISSUE THREAD

**Issue by lxly9** [Lemonszz/Biome-Makeover#245]
When placing lilypads from the chipped mod on water the little stem gets added to the bottom, this would be correct behavior if these lilypads were in the biomemakeover:lily_pad tag. However, these lilypad blocks have a gray stem and use the default lilypad texture but in grayscale. This happens on version Fabric 1.20.1-1.11.4 with Chipped version [Fabric] Chipped 3.0.1

**Comment by Lemonszz** [comment]
Could you clarify how this is a Biome Makeover issue? I'm not sure what you mean by "the little stem gets added to the bottom".

Does the behavior you see stop when you remove Biome Makeover from your modpack?

**Comment by lxly9** [comment]
Oh, it could be that that is actually a wilderwild feature and ive confused the both of them. The stem that I mean is this
![image](https://github.com/Lemonszz/Biome-Makeover/assets/102386118/df029cb3-82ca-4530-840d-4bb36d0c719b)

**Comment by Lemonszz** [comment]
Ah, yeah, that's not from Biome Makeover.

Feel free to reopen if I'm misunderstanding.
