### ISSUE TITLE
mob:moth cann't rendered

### ISSUE THREAD

**Issue by Epicsparta** [Lemonszz/Biome-Makeover#248]
fabric 0.15.1
version 1.19.2
biomemakeover: Biome Makeover 1.19.2-1.6.4
this happen 3 times in 3 differents worlds

Time: 2023-12-28 17:37:22
Description: Rendering entity in world

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_4496 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at party.lemons.biomemakeover.entity.render.MothModel.setupAnim(MothModel.java:104)
	at party.lemons.biomemakeover.entity.render.MothModel.method_2819(MothModel.java:17)
	at net.minecraft.class_922.method_4054(class_922.java:129)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1568)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 21 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method interpolateAngle(FFFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V in fastanim.mixins.json:ModelUtilMixin from mod faster_entity_animations failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap lunade-fastanim-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at party.lemons.biomemakeover.entity.render.MothModel.setupAnim(MothModel.java:104)
	at party.lemons.biomemakeover.entity.render.MothModel.method_2819(MothModel.java:17)
	at net.minecraft.class_922.method_4054(class_922.java:129)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1568)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1039)

-- Entity being rendered --
Details:
	Entity Type: biomemakeover:moth (party.lemons.biomemakeover.entity.MothEntity)
	Entity ID: 386
	Entity Name: Moth
	Entity's Exact location: 443.13, 126.50, -1078.58
	Entity's Block location: World: (443,126,-1079), Section: (at 11,14,9 in 27,7,-68; chunk contains blocks 432,-64,-1088 to 447,319,-1073), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,-64,-1536 to 511,319,-1025)
	Entity's Momentum: -0.04, 0.14, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1568)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: party.lemons.biomemakeover.entity.render.MothRender@2fd9d450
	Location: -9.91,-3.12,57.58 - World: (-10,-4,57), Section: (at 6,12,9 in -1,-1,3; chunk contains blocks -16,-64,48 to -1,319,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Rotation: 81.5625
	Delta: 0.92000866
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1568)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Epicsparta'/347, l='ClientLevel', x=453.03, y=128.00, z=-1136.17]]
	Chunk stats: 151, 151
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,75,48), Section: (at 0,11,0 in -2,4,3; chunk contains blocks -32,-64,48 to -17,319,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 1774 game time, 14555 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	pehkui:debug/render/entity: biomemakeover:moth
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, simplyswords/classic, EclecticTrove-1.19.2-1.3.0.zip, EmbellishedStone-1.19-1.0.0.zip, STONEBORN - 1.19 - V3.2.1.zip, lambdabettergrass/default, Essential (fabric_1.19.2).jar

- **And this are the mods that i use:**

Fabric Mods: 
		additionalstructures: Additional Structures 4.1.2
		advancementplaques: Advancement Plaques 1.4.6
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.18
		alloy_forgery: Alloy Forgery 2.1.1+1.19
		ambientsounds: Ambient Sounds (Fabric) 5.2.13
		architectury: Architectury 6.5.85
		artifacts: Artifacts 7.1.1+fabric
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		autotag-convention: AutoTag Convention 2.0.0+1.19
			autotag: AutoTag 2.0.0+1.19
		balm-fabric: Balm 4.6.0
		bclib: BCLib 2.1.8
		betteradvancements: Better Advancements 0.2.2.142
		betteranimalsplus: Better Animals Plus 1.19.2-11.0.10
		bettercombat: Better Combat 1.7.1+1.19
		betterend: Better End 2.1.7
		betterfortresses: YUNG's Better Nether Fortresses 1.19.2-Fabric-1.0.6
			org_reflections_reflections: reflections 0.10.2
		betterfpsdist: Better FPS distance Mod 1.19.2-3.7
		betternether: Better Nether 7.1.5
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.1
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		biomemakeover: Biome Makeover 1.19.2-1.6.4
		blur: Blur (Fabric) 2.6.0
		bookshelf: Bookshelf 16.3.20
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.7-1.19.2
			maelstrom_library: Maelstrom Library 1.3.1-1.19.2
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		byg: Oh The Biomes You'll Go 2.0.1.6
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		charmofundying: Charm of Undying 6.2.1+1.19.2
		chunksending: Chunksending Mod 1.19.2-2.8
		cleancut: CleanCut 6.0
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v8 8.3.115
		clumps: Clumps 9.0.0+14
		collective: Collective 7.28
		configured: Configured 2.0.0
		connectedglass: Connected Glass 1.1.10
		connectivity: Connectivity Mod 1.19.2-4.5
		controlling: Controlling For Fabric 10.0+7
		corgilib: CorgiLib 1.0.0.34
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		creativecore: CreativeCore (Fabric) 2.9.3
		creeperoverhaul: Creeper Overhaul 2.0.9
		ctov: ChoiceTheorem's Overhauled Village 3.2.6c
		cull-less-leaves: Cull Less Leaves 1.0.6
			conditional-mixin: conditional mixin 0.3.0
		culturaldelights: Cultural Delights Fabric 0.14.10+1.19.2
			terraform-wood-api-v1: Terraform Wood API (v1) 4.2.0
		cupboard: cupboard 1.19.2-2.1
		dark-enchanting: Dark Enchanting 1.0.2+1.19.2
			libgui: LibGui 6.4.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
			omega-config: OmegaConfig 1.2.3-1.18.1
		dataattributes: Data Attributes 1.4.6+1.19.2
		dawn: Dawn API 3.5.0
		debugify: Debugify 2.8.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		doapi: Lets Do Api 1.1.0
			blue_endless_jankson: jankson 1.2.1
		droplight: Droplight 1.0.5
		dungeons_arise: When Dungeons Arise 2.1.54
		dynamic_fps: Dynamic FPS 3.3.1
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.19
		easyanvils: Easy Anvils 4.0.11
		easymagic: Easy Magic 4.3.3
		effective: Effective 1.4
		eldritch_mobs: EldritchMobs 1.13.2
			polymer: Polymer (Core) 0.2.28+1.19.2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.3+1.19.2
			polymer-blocks-ext: Polymer Blocks 0.1.0-alpha.9+1.19.2
			server_translations_api: Server Translations API 1.4.18+1.19.2
		elementa: Elementa 619
		elytraslot: Elytra Slot 6.1.1+1.19.2
		enchdesc: EnchantmentDescriptions 13.0.14
		endermanoverhaul: Enderman Overhaul 0.0.0
		endrem: End Remastered 5.2.0
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		enhancedcelestials: Enhanced Celestials 2.1.0.6
		entityculling: EntityCulling-Fabric 1.6.1-mc1.19.2
		essential: Essential 1.3.0.1+g24ea70f4b2
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.1
		expandeddelight: Expanded Delight 0.2.5.2
		explorerscompass: Explorer's Compass 1.19.2-2.2.0-fabric
		explorify-fabric: Explorify 1.19-1.3.0
		extrakeybinds: ThatRobins Extra Origins Keybinds 0.5.0+1.17-1.19.4
		fabric-api: Fabric API 0.77.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.42+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.9+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.12+def3f86d90
			fabric-networking-v0: Fabric Networking (v0) 0.3.29+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.1.0+ee641e7390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.2+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.33+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.25+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.28+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.13.0+526f2c6790
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.8+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.1
			mixinextras: MixinExtras 0.3.1
		farmersdelight: Farmer's Delight 1.19.2-1.3.10.2
		farsight: Farsight Mod 1.19.2-3.5
			org_jctools_jctools-core: jctools-core 4.0.1
		faster_entity_animations: FastAnim 1.5.6
		ferritecore: FerriteCore 5.0.3
		forgeconfigapiport: Forge Config API Port 4.2.11
		fpsreducer: FPS Reducer 1.19.2-2.1
		fusion: Fusion 1.1.0+c
		fwaystones: Fabric Waystones 3.0.8+mc1.19.2
		geckolib3: Geckolib 3.1.40
			com_eliotlash_mclib_mclib: mclib 20
		globaldataandresourcepacks: Global Data- & Resourcepacks 1.14.5_fabric
		go-fish: Go Fish 1.6.0-1.19.1
		goodall: Goodall 1.2.0
		gpumemleakfix: Gpu memory leak fix mod 1.19.2-1.6
		graveyard: The Graveyard 2.3.3
		graveyard_biomes: The Graveyard Biomes 1.6
		iceberg: Iceberg 1.0.46
		immediatelyfast: ImmediatelyFast 1.2.8+1.19.2
			net_lenni0451_reflect: Reflect 1.3.1
		imst: Immersive structures 2.0.7a
		imst_n: Immersive Structures:Nether edition 1.0.0
		incantationem: Incantationem 1.1.6+1.19
		incendium: Incendium 5.1.6
		indium: Indium 1.0.9+mc1.19.2
		interactic: Interactic 0.1.11+1.19
		inventoryprofilesnext: Inventory Profiles Next 1.10.9
		itemmodelfix: Item Model Fix 1.0.3+1.19
		jade: Jade 8.7.3
		jamlib: JamLib 0.6.1+1.19-1.19.2
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.7
			journeymap-api-fabric: JourneyMap API 1.19.1-1.9-fabric-SNAPSHOT
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
		lambdynlights: LambDynamicLights 2.2.0+1.19.2
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.1.0+1.19.2
		lazydfu: LazyDFU 0.1.3
		leavesbegone: Leaves Be Gone 4.0.1
		legendarytooltips: Legendary Tooltips 1.3.3
		letmedespawn: Let Me Despawn fabric-1.0.2
		libipn: libIPN 4.0.1
		libz: LibZ 1.0.0
		lilwings: Lil' Wings 1.2.3
			milk: Milk Lib 1.0.48
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.0
		magistuarmory: Epic Knights Mod 8.12
		magnumtorch: Magnum Torch 4.2.3
		mcda: MC Dungeons Armors 2.4.4
		mcdw: MC Dungeons Weapons 5.0.13-1.19
			enchant_giver: Enchant Giver 1.3.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		meadow: Meadow 1.2.0
		medievalorigins: Medieval Origins Revival 5.1.9.2+1.19.2
			additionalentityattributes: Additionalentityattributes 1.4.0+1.19.2
			common-protection-api: Common Protection API 1.0.0
		midnightlib: MidnightLib 1.0.0
		minecraft: Minecraft 1.19.2
		modernfix: ModernFix 5.11.1+mc1.19.2
		modmenu: Mod Menu 4.1.2
		mousetweaks: Mouse Tweaks 2.22
		mvs: Moog's Voyager Structures 4.1.1-1.19.2-fabric
		mythicmetals: Mythic Metals 0.17.3+1.19.2
		mythicmetals_decorations: Mythic Metals Decorations 0.5.2+1.19.2
		mythicmounts: Mythic Mounts 1.19.2-7.2
		nameplate: Nameplate 1.1.3
		naturescompass: Nature's Compass 1.19.2-2.1.0-fabric
		netherportalfix: NetherPortalFix 10.0.1
		nullscape: Nullscape 1.2.2
		org_jetbrains_annotations: annotations 13.0
		origins: Origins 1.7.1
			apoli: Apoli 2.6.1
				calio: Calio 1.7.0
				playerabilitylib: Pal 1.6.0
		owo: oωo 0.9.3+1.19
		patchouli: Patchouli 1.19.2-77-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.7.12+1.14.4-1.20.4
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		player-animator: Player Animator 1.0.2
		playerex: PlayerEx 3.5.4+1.19.2
			net_objecthunter_exp4j: exp4j 0.4.8
			opc: Offline Player Cache 0.6.4
			placeholder-api: Placeholder API 2.0.0-pre.1+1.19.2
			projectile_damage: Projectile Damage Attribute 3.2.1+1.19
		prism: Prism 1.0.3
		promenade: Promenade 2.7.1
			terraform-shapes-api-v1: Terraform Shapes API (v1) 4.0.0
		puzzleslib: Puzzles Lib 4.4.3
		quartzelv: Quartz Elevator 2.1.5+1.19
		recipe-book-delight: Recipe Book Delight 0.3.0-1.19.2
			dark-matter-base: Dark Matter Base 2.2.0-1.19.2
			dark-matter-enums: Dark Matter Enums 2.2.0-1.19.2
			dark-matter-minecraft: Dark Matter Minecraft 2.2.0-1.19.2
			dark-matter-recipe-book: Dark Matter Recipe Book 2.2.0-1.19.2
		redirectionor: Redirectionor 1.19.2-3.3.2
		reds_morestructures_mr: Red’s More Structures 1.0.7C
		reeses-sodium-options: Reese's Sodium Options 1.6.4+mc1.19.2-build.93
		relicex: RelicEx 3.3.2+1.19.2
			armorrenderlib: Armor Render Lib 0.2.6
		repurposed_structures: Repurposed Structures 6.3.28+1.19.2
		resourcefulconfig: Resourcefulconfig 1.0.20
		resourcefullib: Resourceful Lib 1.1.24
		rightclickharvest: Right Click Harvest 3.2.3+1.19.x-1.20.1-fabric
		rottencreatures: Rotten Creatures 1.0.1
		roughlyenoughitems: Roughly Enough Items 9.1.682
			error_notifier: Error Notifier 1.0.9
		rpgdifficulty: Rpg Difficulty 1.3.12
		satin: Satin 1.9.0
		servercore: ServerCore 1.3.3-1.19.2
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			me_lucko_spark-api: spark-api 0.1-SNAPSHOT
		simplyswords: Simply Swords 1.47.0-1.19.2
		smoothboot: Smooth Boot 1.19-1.7.1
		smoothchunk: Smooth chunk save Mod 1.19.2-3.5
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		soulsweapons: Marium's Soulslike Weaponry 1.0.2-1.19.2-fabric
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.18
		spark: spark 1.10.37
		starlight: Starlight 1.1.1+fabric.ae22326
		starterkit: Starter Kit 5.4
		structureessentials: Structure Essentials Mod 1.19.2-3.2
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.16
		t_and_t: Towns and Towers 1.9
		terrablender: TerraBlender 2.0.1.136
		thiccpackets: Extra Thicc Packets 1.17-1.19+
		things: Things 0.3.0+1.19
		travelersbackpack: Traveler's Backpack 1.19.2-8.2.33
		treechop: HT's TreeChop 0.18.6
		trinkets: Trinkets 3.4.2
		twilightforest: The Twilight Forest 4.2.357
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			here-be-no-dragons: Here be no Dragons! 1.0.0
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			mm: Manningham Mills 2.3
			porting_lib: Porting Lib 2.1.727+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_accessors: Porting Lib Accessors 2.1.727+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.727+1.19.2
				porting_lib_base: Porting Lib Base 2.1.727+1.19.2
				porting_lib_common: Porting Lib Common 2.1.727+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.727+1.19.2
				porting_lib_entity: Porting Lib Entity 2.1.727+1.19.2
				porting_lib_extensions: Porting Lib Extensions 2.1.727+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.727+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.727+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.727+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.727+1.19.2
				porting_lib_models: Porting Lib Models 2.1.727+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.727+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.727+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.727+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
		ultris_mr: Ultris: Boss Expansion 5.6.7f
		universalcraft: UniversalCraft 318
		veinmining: Vein Mining 1.1.3+1.19.2
			spectrelib: SpectreLib 0.12.6+1.19.2
		vigilance: Vigilance 295
		vinery: Vinery 1.3.12
		voidtotem: Void Totem 2.1.0
		wabi_sabi_structures: Wabi-Sabi Structures 1.2.0
		whisperwoods: Whisperwoods 1.19-2.1.1
		wondrouswilds: Wondrous Wilds 1.19.2-1.1.6
		xps: Xp Obelisk 0.4.9-r+1.19.2-Fabric
		xps_additions: XP Obelisk Additions 0.1.9-r+1.19.2-Fabric
		yet-another-config-lib: YetAnotherConfigLib 2.2.0-for-1.19.2
		yigd: You're in Grave Danger 1.4.9
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.10

**Comment by Lemonszz** [comment]
We're not supporting 1.19.2 anymore, sorry.

You could try it without "FastAnim", the crash points to it.

**Comment by Epicsparta** [comment]
Yes, it works, sorry for the inconvenience.
