### ISSUE TITLE
Bottle o' Lighting doesn't work as it should.

### ISSUE THREAD

**Issue by RDKRACZ** [Lemonszz/Biome-Makeover#26]
There are no visuals, only the thunder. Entities aren't set on fire too. Can we get an explanation of what this new effect is doing? The one after being hit by Bottle o' Lighting.

**Comment by Lemonszz** [comment]
The curseforge page explains it in detail.

 _if the Lightning Bug is captured in a "Bottle o' Enchanting" it will give the player a Bottle o' Lightning, an item that can be thrown like a splash potion to transform any mobs affected by lightning (i.e. villagers to witches, pigs to zombified piglins, or creepers to charged creepers), and will inflict any mobs within its radius with the Shocked effect. The Shocked effect temporarily reduces a mobs' or player's maximum health by one heart per level of the effect, up to 4 levels._
