### ISSUE TITLE
Water fog colour does not match water colour in mushroom biomes

### ISSUE THREAD

**Issue by FewerFlaws** [Lemonszz/Biome-Makeover#28]
The surface of water has been changed to purple but the waterfog has not been adjusted to match.  Even if vanilla waterfog colour is preferred it should be included in the mod for compatibility purposes.  The screenshots below were taken with Biome Makeover installed alongside Bedrock Waters.

![2021-01-22_21 04 02](https://user-images.githubusercontent.com/75643699/105569315-9c107800-5cf5-11eb-9e87-dc8e3f9c7e39.png)
Mushroom Fields: the surface doesn't match.

![2021-01-22_21 04 26](https://user-images.githubusercontent.com/75643699/105569379-fad5f180-5cf5-11eb-81c4-2469a77f01a9.png)
Lukewarm Ocean: swimming in water!

**Comment by Lemonszz** [comment]
I believe this is on bedrock water's end. They need to use the fabric biome modification api.

Feel free to open if that's not the case.
