### ISSUE TITLE
Tadpoles neither spawn nor move.

### ISSUE THREAD

**Issue by FewerFlaws** [Lemonszz/Biome-Makeover#29]
Tadpoles should spawn naturally in swamps, and they should move around a little more.  Right now they do not spawn naturally, and their move speed is so low they seem to stay in place while constantly trying to swim.

**Comment by Lemonszz** [comment]
There's no point to them spawning naturally as they'll just grow up into toads.

They will move around if they have enough space, but their fairly low speed in intended.

**Comment by FewerFlaws** [comment]
Baby animals of other sorts spawn naturally.  But I can implement that on my end anyways =]
