### ISSUE TITLE
Willow & Cypress Boats Appear As Balsa

### ISSUE THREAD

**Issue by nephatrine** [Lemonszz/Biome-Makeover#30]
I'm on MC 1.16.5 using Biome Makeover `biome-makeover-1.16.4-1.2.9.jar`. All three boats added by this mod look the same - they all look like the balsa wood. The icons themselves are correct, just once placed in world they are not.

**Comment by Lemonszz** [comment]
I can't recreate this in a 1.16.5 (or 16.4) environment with nothing but Biome Makeover + Fabric API.

I think I'd need more information to see if that's an issue on our end.

Are you using the latest Fabric API?
Are you on a server or singleplayer?

**Comment by Lemonszz** [comment]
I'm going to close this for name, if you/someone else has more information, let me know.
