### ISSUE TITLE
Config to blacklist specific biomes from gaining new swamp plants/trees

### ISSUE THREAD

**Issue by saltyseadoggo** [Lemonszz/Biome-Makeover#33]
Biome Makeover adding its own new plants and trees to any swamp biome has mixed effects on biomes that have their own, non-vanilla trees and plants. For example, [Terrestria](https://github.com/TerraformersMC/Terrestria) and its `terrestria:cypress_swamp` biome end up with two types of cattails and cypress trees, and some BYG biomes that are not swamps, such as `byg:fresh_water_lake` or `byg:polluted_lake` end up turning into swamps with the addition of this mod's foliage. One can disable these modded biomes for continuity at the cost of their content. I think it would be better to add a configuration file with a field for biome ids to blacklist from Biome Makeover's plant generation to resolve this as they see fit.~

**Comment by Lemonszz** [comment]
Moving config request discussion to a separate issue. #65
