### ISSUE TITLE
Swamp cypress planks are hard to distinguish from jungle planks

### ISSUE THREAD

**Issue by saltyseadoggo** [Lemonszz/Biome-Makeover#34]
Swamp cypress planks look a fair bit similar to jungle planks, to where it can be hard to tell them apart at a glance. I feel like they miss an opportunity to stand out from vanilla plank offerings as they are currently. Unfortunately, I'm not quite sure how I would adjust them to make them distinguished.

![2021-02-04_11 53 15](https://user-images.githubusercontent.com/69029346/106948268-546bf200-66e0-11eb-81f1-524926ba9854.png)

**Comment by Lemonszz** [comment]
We're aware they're similar, but we don't see this as a problem. You can mix the two and create subtle patterns, great for small details.
