### ISSUE TITLE
Make the custom creative side tabs into its own mod

### ISSUE THREAD

**Issue by Noaaan** [Lemonszz/Biome-Makeover#35]
Coming here from a suggestion from RDKRACZ https://github.com/Noaaan/MythicMetals/issues/30.
The CreativeInventoryScreenMixin is a really good idea, I love how it looks. I recommend making it into a library of sorts so more mods could implement this easier.

**Comment by Lemonszz** [comment]
I'm not really interested in making any libraries. The mod is MIT, you're welcome to take and improve upon the code if you want to use it.
