### ISSUE TITLE
Plainier Plains (suggestion)

### ISSUE THREAD

**Issue by KrisTheLightner** [Lemonszz/Biome-Makeover#38]
(based on [this](https://www.reddit.com/r/minecraftsuggestions/comments/m4shwm/flatter_plains_biome/) post)
Some ideas for Plains Update:
1) Ponds should be bigger and rather. Also they should be surrounded by stone, like lava lakes
2) Less exposed caves (in Plains biome)
3) Flatter generation (in Plains biome)
4) Oaks should be replaced with Apple Trees, new wood type (in Plains biome)
5) No more Apples from Oak and Dark Oak Leaves
6) Apple Trees Leaves with Apples (idk how to name properly) - if you right-click on them with Shears, you'll get 2-3 Apples. Then this block turns into regular Apple Tree Leaves. This type of foliage should appear sonetimes on apple trees (logic, yep). There should be no way to turn regular Apple Tree Leaves into Apple Tree Leaves with Apples (just like regular Azalea Leaves from 1.17 snapshots cannot be turned into Flowering Azalea Leaves)

Sorry for bad English...

**Comment by Lemonszz** [comment]
We've taken note of these - just closing to clean up.
