### ISSUE TITLE
Compatability with enchantment descriptions mod?

### ISSUE THREAD

**Issue by NixityNull** [Lemonszz/Biome-Makeover#44]
It would be very helpful to be able to know what each curse does and this mod is very helpful with enchantment tooltips. ( https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions.)

It should be relatively easy to add descriptions, but knowing you have other, more important issues to deal with, there is no need to rush.

**Comment by Lemonszz** [comment]
Will be in 1.4.0.
