### ISSUE TITLE
Lily pads and willow leaves have the wrong color with sodium

### ISSUE THREAD

**Issue by legosteenjaap** [Lemonszz/Biome-Makeover#48]
The colors are totally inconsistent between sodium and vanilla.

![image](https://user-images.githubusercontent.com/50271899/117359347-8c3d2e00-aeb7-11eb-96e3-ed251d72c944.png)
Biomemakeover 1.3.8 + sodium 0.1.0

![image](https://user-images.githubusercontent.com/50271899/117358947-0caf5f00-aeb7-11eb-9a69-622d1febbab9.png)
Biomemakeover 1.3.8 without sodium 

Before the dark forest update the colors were also different, but not that noticable.
![image](https://user-images.githubusercontent.com/50271899/117358324-4f246c00-aeb6-11eb-9dcd-b749358626f9.png)
Biomemakeover 1.2.13 + sodium 0.1.0

![image](https://user-images.githubusercontent.com/50271899/117358569-9a3e7f00-aeb6-11eb-9734-b676fb790927.png)
Biomemakeover 1.2.13 without sodium

used fabric api 0.33.1

**Comment by Lemonszz** [comment]
Thanks for the detailed report - I'll look into it.

**Comment by Lemonszz** [comment]
I believe this is fixed for upcoming 1.18.1 release.

Thanks for the report (and sorry for the late response!)
