### ISSUE TITLE
Failing to load or create world (lithium compat.?)

### ISSUE THREAD

**Issue by Artheow** [Lemonszz/Biome-Makeover#5]
Hi, been following the badlands update on fabricord and jumped right into this new update but worlds refuses to load/create both client and server side.I got this from the server one: https://pastebin.com/43v70GHn

**Comment by Lemonszz** [comment]
Fixed in V1.1.1, though I'm marking the update as a beta as it was pretty hastily done and I'm about to go to bed.

Seems to be fixed and working fine, but I'll leave this issue open until I can fully verify tomorrow.

**Comment by Lemonszz** [comment]
1.1.2 is released. If this is still a problem, please let me know!
