### ISSUE TITLE
Peat Farmland Issue

### ISSUE THREAD

**Issue by SpinnyBoiii** [Lemonszz/Biome-Makeover#50]
I was testing the speed of peat farmland vs regular farmland with 8x8 villager automatic farms in creative mode and noticed that the villager woudnt start planting if there was no regular farmland in range.
Is this intended as a trade-off for the boosted speed by any chance?

**Comment by Lemonszz** [comment]
So you're saying they'll plant on peat, but only if there's some regular farmland?
 That sounds like a bug, they're supposed to be able to plant on peat.

**Comment by SpinnyBoiii** [comment]
thats exactly it yes

**Comment by Lemonszz** [comment]
Thanks - Yeah that's unintended, I'll look into it.
