### ISSUE TITLE
[1.16.5-1.3.8] Paydirt can be placed floating on water

### ISSUE THREAD

**Issue by TelepathicGrunt** [Lemonszz/Biome-Makeover#51]
Image below is the Paydirt blocks found floating on water in World blender's dimension (my mod imports features). But this issue should be able to be found in the overworld as well if biomes dip below sealevel where the feature places the blocks.  Might be due to using world surface heightmap instead of ocean floor heightmap which would return the topmost land even in oceans
![image](https://user-images.githubusercontent.com/40846040/120529213-3f5f5100-c3aa-11eb-9e24-88ed4891c00d.png)

**Comment by TelepathicGrunt** [comment]
Do note, this could be a weird interaction with another mod's feature tho or due to paydirt replacing lilypads instead of my heightmap thing as it seems the feature doesnt do heightmaps. more testing is needed

**Comment by TelepathicGrunt** [comment]
i made a datapack to add lilypads to badlands and sure enough, I found a floating paydirt. I guess a better solution is to check if the paydirt is replacing a full solid block or start using certain tags to replace only the right blocks (like sand, sandstone, and overworld_base_stone tags or something) 
![image](https://user-images.githubusercontent.com/40846040/120533563-d928fd00-c3ae-11eb-8e7b-ac15b9db76c8.png)

**Comment by Lemonszz** [comment]
Fixed for upcoming 1.18.1 release.

Thanks for the report (and sorry for the late response!)
