### ISSUE TITLE
Game Crashes on start up with Biome Makeover

### ISSUE THREAD

**Issue by toErIpNid** [Lemonszz/Biome-Makeover#53]
MC Version: 1.16.5
Fabric Version: 0.11.5
Mod Version: 1.3.8

Log:
[latest.log](https://github.com/Lemonszz/Biome-Makeover/files/6645714/latest.log)

**Comment by Lemonszz** [comment]
That log doesn't contain a crash nor does it mention Biome Makeover at all (as in you don't have it installed).
