### ISSUE TITLE
Biome Makeover crashes modpack on startup: Uncaught Fatal Exception Code 1

### ISSUE THREAD

**Issue by toErIpNid** [Lemonszz/Biome-Makeover#54]
MC Version: 1.16.5
Fabric Version: 0.11.5
Mod Version: 1.3.8

Log: 
[latest.log](https://github.com/Lemonszz/Biome-Makeover/files/6652620/latest.log)

**Comment by Lemonszz** [comment]
Log doesn't contain a crash, open up another issue if you have more information.
