### ISSUE TITLE
This mod is trying to invoke a Sponge URL when running it on a server.

### ISSUE THREAD

**Issue by githubbingitup** [Lemonszz/Biome-Makeover#58]
Running on a 1.16.5 Fabric server. The only other mod is Fabric API, latest version .36.

Just found this strange and it only comes up from this specific mod.
What does it mean and is it an issue?

https://imgur.com/Pnnglqx

**Comment by Lemonszz** [comment]
its a package name from sponge's mixin library. this error is annoying but harmless. See the #40

**Comment by githubbingitup** [comment]
thank you for letting me know, appreciate ur work!
