### ISSUE TITLE
Questions and suggestions.

### ISSUE THREAD

**Issue by RDKRACZ** [Lemonszz/Biome-Makeover#6]
Could You make the ghost towns generate in other biomes too? I think they aren't looking biome-specific so why not? The same for newly added cactuses, I would like to see them on deserts.
Can You tell us what biome do You plan to upgrade in the near future?
I saw a suggestion about rivers on curseforge, it's a good idea but there are already mods for better rivers. IMO You should consider deserts as the next todo because they are boring in vanilla Minecraft. There aren't any specific mobs there, husks don't count, they are just retextured zombies. You could add a bird because Minecraft has only parrots. It could be aggressive, a vulture looking one. I love the new mob added in the Badlands update so I trust You with this.

**Comment by Lemonszz** [comment]
Thanks for the suggestions.

We're working on the biomes one at a time. We'll look into what existing features fit into each biome as we get to them.
