### ISSUE TITLE
Ghosts are not considered undead mobs

### ISSUE THREAD

**Issue by Brun333rp** [Lemonszz/Biome-Makeover#60]
Despite the fact they are clearly dead, they are not considered undead mobs.

**How to Reproduce**

- First way is to summon a Ghost next to a Wither. By doing this, you'll notice that it attacks the Ghost.

- Second way is to throw a healing potion or a damage potion on a Ghost. Notice that they work just like in a living mob, instead of in the opposite way like it happens with the undead;

- Third way is by attacking a Ghost with a Smite-enchanted weapon. Instead of receiving additional damage, it will suffer normal damage, as if the weapon is not enchanted at all.

**Comment by Lemonszz** [comment]
Fixed for upcoming 1.18.1 release.

Thanks for the report!
