### ISSUE TITLE
Newest Update crashes minecraft?

### ISSUE THREAD

**Issue by hanzotitmada** [Lemonszz/Biome-Makeover#64]
[
[crash-2021-09-17_10.36.17-client.txt](https://github.com/Lemonszz/Biome-Makeover/files/7186485/crash-2021-09-17_10.36.17-client.txt)
](url)
To be honest i have no idea why this isn't working, i put the file into my mod folder and it just can't load minecraft, i have used the last version of biome makeover and it worked fine? i don't really understand crash reports so im not sure what's wrong :c

**Comment by Lemonszz** [comment]
update fabric api
