### ISSUE TITLE
Cowboy hat incorrectly placed on head.

### ISSUE THREAD

**Issue by superon** [Lemonszz/Biome-Makeover#7]
by odd i mean it sort of makes any trinket related items a player is wearing go out of sync with the player model..
night vision goggle move faster than the player head and belt items get attached to the "head layer" too.
biome-makeover-1.16.4-1.1.5
you can see what i mean on the head slot here
https://www.twitch.tv/videos/851529445 at about 1:37:30
modlist ripped from a recent crash report
https://pastebin.com/M00wn1hQ

**Comment by Lemonszz** [comment]
I have a feeling that's a conflict with whatever mod adds those night vision goggles, I'll leave this issue open in case others run into something similar to we can track down the exact conflict.

**Comment by superon** [comment]
oh, yeah it definitely is, between biome makeover artifacts and trinkets.
artifacts requires trinkets
https://imgur.com/xJ78BsS
