### ISSUE TITLE
Server timeout due to mod?

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [Lemonszz/Biome-Makeover#70]
Upon finding this structure on the server it times out the server and crashes it. 
![image](https://user-images.githubusercontent.com/7256303/150640210-43f46c6c-f024-4240-a198-1d2ed9fa0cb0.png)

I tried to reproduce the issue in singleplayer but couldnt do it consistently. It usually works in singleplayer but never in multiplayer.

Modpack: Benchmark II 1.18.1 0.6.4 newly generated world (With the oh biomes mod removed. )
Seed: 5924450926579097189
Location: 1294 77 -2720

Trying to go inside or loading the entire structure times the server out.
Configs changed from default: Server render distance changed to 15. All other options remain the same.

Crash report doesnt mention this mod specifically but yet here it is: https://pastebin.com/Aa2HmWFY

**Comment by RSAmaro** [comment]
I'm also having the same issue, same modpack, on a server.
Seed: -6343544224602108497
![image](https://user-images.githubusercontent.com/37576434/150662963-e3fb4a33-6b9f-44e7-96a9-70340ec759c1.png)

**Comment by Lemonszz** [comment]
Thanks this was fixed in 1.4.3!

**Comment by Nydid** [comment]
Still crashing in 1.4.3

https://pastebin.com/6Nz2N4Tn
