### ISSUE TITLE
Could your mod have be incompatible with FabricSeasons?

### ISSUE THREAD

**Issue by TheButterbrotMan** [Lemonszz/Biome-Makeover#71]
Its snowing in sparse_jungle in summer, probably it is your mod. Before i added him all was summer, now its winter :(

Im using 1.4.3 of your mod.

**Comment by Lemonszz** [comment]
Report it to Fabric Seasons, I don't know anything about that mod. I doubt anything we do would cause that.

**Comment by TheButterbrotMan** [comment]
https://www.curseforge.com/minecraft/mc-mods/fabric-seasons
