### ISSUE TITLE
[Compatibility] Enable equipping enchanted totem in amulet slot if Trinket of Undying is loaded

### ISSUE THREAD

**Issue by teleheel** [Lemonszz/Biome-Makeover#75]
It would be nice if the Enchanted Totem of Undying could be equipped in the amulet trinket slot when [Trinket of Undying](https://www.curseforge.com/minecraft/mc-mods/trinket-of-undying-fabric) is installed. Right now players will tend to use the normal totem as this frees up the offhand.

**Comment by pawbap** [comment]
Seconding this! It would be nice, at least as a toggleable configuration to enable Trinket support.

**Comment by Lemonszz** [comment]
I've (finally) looked into this and it's likely best that someone else develop this as an addon mod.  

I do think this would be cool to have, but I'm not willing to develop it.

It would be best to also support Curios for the Forge side and I'm not willing to take on the burden of supporting multiple 3rd party APIs for such a minor feature. 

This is a year late, so you probably don't care, but sorry anyway!
