### ISSUE TITLE
infinite enchants !

### ISSUE THREAD

**Issue by Chuunkyz** [Lemonszz/Biome-Makeover#78]
if you have a mod that adds an enchant grinding functionality like infusion table, grind enchants or disenchanting tables, you can use the altar over and over and get fortune 65536 if you want

**Comment by Lemonszz** [comment]
We're balanced around vanilla. 

Other mods can fix this by either retaining NBT tags on their items or failing to do whatever they do if the item has the "BMCursed" NBT tag.

**Comment by Chuunkyz** [comment]
you're serious ?
all the mods can't provide support for your mod, and not having the ability to grind the enchant makes the altar completely useless !
can you just check if there's an enchant that is higher that what vanilla can do to prevent the item to be used in the altar ??

**Comment by Lemonszz** [comment]
You can't grind curses off in vanilla, that's kinda the whole point of them. Mods breaking that balance isn't my concern.

**Comment by Lemonszz** [comment]
I probably could do that check, but it may be a while until I get around to it.

**Comment by Chuunkyz** [comment]
okay, just keep in mind 99% of modpacks have that feature
