### ISSUE TITLE
Spooky Log Warning

### ISSUE THREAD

**Issue by greensad** [Lemonszz/Biome-Makeover#83]
**This warning in log:** 
[Server thread/WARN]: Couldn't create template entity of biomemakeover:adjudicator (class net.minecraft.class_1297)... Defaulting to empty
[Server thread/WARN]: java.lang.IllegalStateException: Should always be able to create a chunk!

**Full Log:** https://paste.ee/p/0ZBus

**Comment by Lemonszz** [comment]
you are correct, that is spooky.
