### ISSUE TITLE
Moth sound does not stop after killing it

### ISSUE THREAD

**Issue by MtnDrew** [Lemonszz/Biome-Makeover#84]
Playing 1.18.1 Forge Version. When you kill a giant moth, the loud sound that plays alongside it, I'm assuming wing beats, does not disappear, it will stay at a fixed point in the area, and if it's anywhere near your house, you're screwed. Exiting and reloading seems to fix it, but that shouldn't have to be done. 

Forge Version 39.0.75
Biome Makeover newest version.

Beautiful mod by the way, swamps look incredible

**Comment by Lemonszz** [comment]
I can't recreate this, perhaps another mod interfering?

I'm going to close this for now, but if you've got more information, I can reopen it.
If you've got a video of this happening, that would be helpful.

**Comment by MtnDrew** [comment]
Oh wow you're right. I just updated to your newest release, and in my modded game the weird ambience sound still spawns around the moths, but with this mod isolated that background sound isn't there at all. 

You were probably wondering what the heck i was talking about hahaha. I'll have to do some testing to see what other mod randomly adds a sound to your moth, that is really strange.

**Comment by Lemonszz** [comment]
The moth does have a flapping sound, but it's fairly subtle, so I figured you were talking about that. 

Interesting that it's a completely different sound.

**Comment by MtnDrew** [comment]
Oh,you're right. I couldn't hear it at first because it was so subtle when it's working correctly, but it is there..

I think it's the same sound just amped up like there were multiple going on in the same place. I haven't figured out what mod does it yet, but I'll keep testing cause it's most likely removeable. 

But seriously this mod paired with hexerei makes swamps the best biome in the game, I don't even care that both mods add willow trees they both look great. Seriously good job.
