### ISSUE TITLE
(1.18.2 Forge) Weird placement of BM's lilypads in swamp rivers

### ISSUE THREAD

**Issue by BugmanBugman** [Lemonszz/Biome-Makeover#89]
![2022-03-15_00 42 59](https://user-images.githubusercontent.com/40730042/158317039-6af4662a-21e1-4390-924b-c26c96fb5aba.png)
![2022-03-15_00 42 38](https://user-images.githubusercontent.com/40730042/158317046-3b99a8f1-e753-4483-bb3d-f4e6fb122adb.png)
![2022-03-15_00 42 54](https://user-images.githubusercontent.com/40730042/158317047-eff61a14-e479-42c8-8c37-1c3c05f8a39d.png)

**Comment by Lemonszz** [comment]
Odd. Is that a custom swamp river biome? If so, from what mod? 

In your last picture, it also looks like there's one underwater.

**Comment by Lemonszz** [comment]
Just confirmed it for myself, it happens in vanilla biomes. Thanks for the report.
