### ISSUE TITLE
Ticking Entity crash on server

### ISSUE THREAD

**Issue by sirben99** [Lemonszz/Biome-Makeover#92]
Hey!

When someone goes into a specific area on my server, theyr game crashes. The crashlog has this mods name spammed everywhere, but it is in a modpack so im not 100% sure its totally this mods fault, but i desided to report this anyway just incase it is.

Minecraft version: 1.18.2
Modloader: Forge (I coudnt find a seperate issue tracker for forge, so i assume posting this here is fine)
Biome Makeover: 1.4.12
Forge: 40.0.17

Crashlog:
[crash-2022-03-21_16.13.22-client.txt](https://github.com/Lemonszz/Biome-Makeover/files/8316692/crash-2022-03-21_16.13.22-client.txt)

Ben

**Comment by Lemonszz** [comment]
Thanks for the report - uploading 1.4.13 that has the fix.
